# Public Adminstration Real Exam {#pa-real}

This chapter provides an example of a full written comprehensive exam. In this common format, there is [a required question](#pa-req) that every student must answer, which generally is intended as a broad field literature review. In this exam, that question asks students to review the major schools of thought and theories associated with the classical school of public administration. Following the required question, five optional questions are provided to the student, who must select two to answer. Generally, these are a little shorter in length compared to the required question, but that is not always true. In the examples provided, I selected a fairly lengthy exam, hoping to provide you with more material to think about and synthesize with your own work as you prepare for exams.

## Required Question: {#pa-req}
> What is the classical theory in public administration? Who are the classical theorists and what are some of their arguments? What led to the rise of other theories/schools such as human behavior and contingency? Describe the theorists and ideas associated with the various schools. What are the strengths and weaknesses of each approach?

### Public Administration: Classical Roots & ‘New’ Branches
As a discipline, public administration is a study in unresolved and unresolvable tensions. The term ‘public administration’ itself is difficult to define perfectly: Is it the professional practice of running public and non-profit services, or the academic study of that work that seeks to (Marini, 2000, p. 3) “understand, develop, criticize, and improve that professional practice as well as train individuals for that professional practice”? Does running a government differ from running a business? How intertwined are politics and administration? How intertwined should they be? As we confront the problematic tradeoffs in public policy, should we pay more attention to facts or values? 

This essay will review the traditions of  primarily academic public administration, though its practitioners make appearances as well – like attempts to divide politics from public administration, attempting to describe American public administration through only its theorists is a doomed effort. The essay proceeds as follows. In the first section, I review the co-founding of America with the first examples of public administration norms in the acts of George Washington and the administrative structures of Alexander Hamilton. In the second section, the essay recounts the foundation of classic public administration through the works of its first theorists. In the third section, the essay covers the behavioralist and contingency movements in public administration. The fourth section details how the scholars thought about the public/private dichotomy in administration, and following that looks at the famous debate between Herbert Simon and Dwight Waldo. In the fifth section, the schools of New Public Administration, New Public Management, and New Public Governance are compared, before the essay closes with a short conclusion.

### The Founding

The dilemmas and tensions that the field of public administration is concerned with today are to a great degree the same that have been of concern from the moment of the nation’s founding. The Constitution set forth the framework that the nation’s Founders believed gave the nation a coherent way of addressing those dilemmas, but did not include detailed instructions on how to implement that framework (Rohr, 1986). In the centennial year of the Constitution, Woodrow Wilson, often acknowledged as the first scholar of public administration, would highlight the challenge (Wilson, 1887): “It is getting to be harder to run a constitution than to frame one.” The constitution was framed, but it was left to early efforts by George Washington and Alexander Hamilton to sketch out the institutional foundations that were necessary to run a constitution.

Washington and Hamilton provided the most impactful early examples of how to administer a new nation: A system that holds service to the public as its first principle, and a blended economic, commercial, and military union that could prevail in the storm of state-based interests that would confront the nation. 
George Washington was America’s first president, and thus, the nation’s first executive administrator. Without binding precedent to guide him, Washington’s actions would themselves become the guide for all that followed. Key among his challenges was the creation of the tools to run the constitution, a challenge that for many public administration scholars remains the highest calling for the field. Washington was well aware that as the first president, his actions would reverberate throughout the nation’s future history. As such, he believed the foundation of his actions needed to be firmly set in principle. As he wrote to James Madison (quoted in Cook & Klay, 2015, p. 76), “As the first of everything, in our situation, will serve to establish a Precedent, it is devoutly wished on my part, that these precedents be fixed on true principles.” 

Among his first actions was establishing a public administration, and the ‘true principle’ Washington tied it to was the public wishes and affection. In other words, public administration should rest upon service to the public will. In his 1791 address to Congress, Washington tied the establishment of the direction of the nation’s public administration directly to the public will (Cook & Klay, 2015, p. 77):
“It is desirable on all occasions, to unite with a steady and firm adherence to constitutional and necessary Act of Government, the fullest evidence of a disposition, as far as may be practicable, to consult the wishes of every part of the community, and to lay the foundations of the public administration in the affection of the people.”

The rough sketch of how to establish a public administration may have been penciled in by George Washington, but it was the hand of Alexander Hamilton that inked in depth and detail. Like Washington, Hamilton was a hero of the Revolutionary War, and he would establish and administer the signal public agencies of the first decades of the new republic (Green, 2019). Much of Hamilton’s approach to public administration is not found in the Constitution he helped create, but in the Federalist papers (Hamilton, Madison, & Jay, 2009) that defended the Constitution to a nation distrustful of a new Federal nation. Hamilton was responsible for authoring approximately 50 of the Federalist Papers, and he saw that the government could not solely be about checking power among the three branches, it would also have to enable action. Hamilton’s concept of ‘partial agency’ meant that powers should be blended among the executive, legislative, and judicial branches, such that the three institutions would collaborate to address the problems of the nation. 

His Federalist co-conspirator James Madison was a patrician elite who was focused on keeping the federated states civil, especially in regards to interstate trade. However, it was Hamilton who saw that the federal government should seek that civility explicitly through the development of a complex economic union. To accomplish that vision, Hamilton spent a great deal of his time enhancing executive power. Hamilton saw that the young nation’s survival would require an intricate bonding of the commercial and military functions of the state. Critical to that bonding was a strong defensive military capability, and as Secretary of the Treasury, Hamilton oversaw many of the first efforts in that domain. Green gives a sense of Hamilton’s influence and scope as he shaped American defensive capabilities in a variety of administrative contexts (Green, 2019, p. 156): 

> “…he attended to the organization and management of the Department of War, and through his management of the Customs Service and a fledgling Coast Guard, he oversaw the protection of harbors from French privateering as the French Revolution ensued. He also equipped militias and helped Washington lead in the successful effort to quell the Whiskey Rebellion in western Pennsylvania in 1794. When war loomed with France in the late 1790s, he returned to the military as a major general, second-in-command to General Washington, serving also as inspector general of the Provisional Army until 1800. He laid extensive plans and lobbied hard for the establishment of the navy, for the outfitting of a small standing army, and for professional military academies in which to train military leaders and subordinate officers in matters ranging from broad military policy to the technology of warfare.”


As he discusses in Federalist essays 23-29 (Hamilton et al., 2009), Hamilton believed a permanent military establishment would eventually become necessary to secure the republic. However, distrust of centralized federal power among Anti-Federalists was strong and able to prevent the establishment of a fulltime federal military until after the Civil War. 

We should not underestimate Hamilton’s impact on public administration based on whether an institution was or was not established, because it is his vision that so strongly permeates how we think about public administration even today. The controversies Hamilton confronted were often left unresolved, and persist today. Hamilton was born a member of the lower socioeconomic class, and knew what it meant to be treated as a second-class citizen. Hamilton even suggested that indigenous and Black Americans should be treated as citizens (though he famously did not include women in his progressive vision). Even today America has not resolved its racial or gender inequality (Riccucci & Ryzin, 2017), but in Hamilton’s day, that idea was genuinely radical. Hamilton sought social revolution through commercial and economic revolution. His successes come to us today as unresolved questions on public versus business administration. Perhaps the most lasting unresolved controversy is Hamilton’s view that there was no politics and policy dichotomy: “Administration and policy merged seamlessly in his mind, each conditioning the other” (Green, 2019).

The founding of the American nation and construction of its initial administrative scaffolding were successful in setting the stage for a constitutional public administration, though the imprinting of the separation of powers in the constitutional arrangement would never disappear from the country’s administrative structures (Kettl, 2015; Rosenbloom, 2016). A system of addressing the controversies resulted in regularized processes of administrative law. The Constitution’s framers "created a certain ambivalence in the status and direction of American public administration" (O’Toole, 1987).  The Constitution embedded the concept of separation of powers the American consciousness, and so it should be no surprise that as the administrative state was founded, there were efforts to instill a similar balance by dividing politics and policy. 

The Pendleton Act, also known as the Civil Service Act of 1883, is an example of attempts to divide politics from administration (Theriault, 2003). The act aimed to insulate the bureaucracy from political influence, and "even more obviously represented an effort to enact the dichotomy" (O’Toole, 1987). Before Wilson introduced his own dichotomy to public administration, there were efforts to legislatively do the same to the practice of administration, such as the Budget and Accounting Act of 1821 - "probably the greatest landmark of our administrative history except for the Constitution itself" (Emmerich, 1971). Similarly, the Hatch Act of 1939 legislated the dichotomy even further by prohibiting federal employees (and some state and local by 1940 amendment) from participating in most partisan political activities.

### Classic Public Administration

The first century of the young nation established a public administration apparatus, but it took that century before any scholarly attempt to study it began. Woodrow Wilson was the first to do so in 1887. Though much later he would become president himself, at the time he was interested in government and how to best understand how a government should organize its efforts. In his article “Study of Administration” (Wilson, 1887), he argued that the complexity of government meant that the best was to study it was from two perspectives: the politics found in the legislative function, and the public administration found in the executive functions of government. This gave birth to a politics and policy dichotomy that would dominate our academic understanding of public administration until late in the 20th century (Goodnow, 2017). Though Wilson acknowledged that the two areas of government were intertwined, his on the dichotomy was an academic convenience to simplify the study of it. Wilson argued that the politics of governing could best be understood when it was intentionally isolated from the administration of political decisions. In this early Wilsonian view, decisions about ‘who gets what, when, and how’ (Lasswell, 1936) are best understood by studying the political and legislative (who gets what, when), separate from the executive actions to complete politics decisions (how). Wilson sought to scientifically uncover the principles that would enable public officials to run the Constitution, by establishing the study of public administration as a field of study separate from politics. 

Classic public administration scholarship was dominated by systematized and hierarchical theorizing, exemplified in Frederick Taylor’s (1914) ‘scientific management, and Luther Gulick’s (1937) acronym POSDCORB: (planning, organizing, staffing, directing, coordinating, reporting, and budgeting).  Neither theory is useless or unused, even today. Taylor was an engineer interested in applying the scientific method towards management, and finding the single best way to organize human effort. He saw scientific management as putting greater demands on "management" and easing the work of the worker. Taylor advocated a scientific approach, to move the knowledge contained in the workman's heads onto paper where it could be studied, best practices extracted, and then propagated to other systems. In his view, this would lead to minimal conflict between workmen and management. 

The embrace of Taylorism and scientific management was inexorably linked to an abstraction of the laborer, a view that has been called the “productivism” of late 19th and early 20th-century management (Rabinbach, 1992). Productivism was a view of human labor as (Scott, 1999, p. 98) “a mechanical system which could be decomposed into energy transfers, motion, and the physics of work.” In America, Taylor is responsible for establishing the technocratic framework in which to measure and administer that mechanical system (Maier, 1970). Taylorism was not a political system, or even a democratic one, but instead played to the high modernist, utopian visions (Scott, 1999) in America and beyond (Rabinbach, 1992, p. 272): 

> “Taylorism and technocracy were the watchwords of a three-pronged idealism: the elimination of economic and social crisis, the expansion of productivity through science, and the reenchantment of technology. The vision of society in which social conflict was eliminated in favor of technological and scientific imperatives could embrace liberal, socialist, authoritarian, and even communist and fascist solutions. Productivism, in short, was politically promiscuous.”

The United States entered World War I under the presidential leadership of Woodrow Wilson, who is also often recognized as the first formal scholar of public administration (Wilson, 1887). The bureau men of public administration embraced Progressive era ideals that were born in rejection of the atrocities of World War I, and further, an optimism that industry and science that would lead the country to a new golden administrative age (Stivers, 1995, 2002). Progressive reformers were informed by the pragmatists of an earlier decade, such as John Dewey, who was distrustful of the absolute reason imposed by the Hegelian ideal of the state (Dewey, 1915), and especially its institutional form found in the Prussian and Germanic military states. As Spicer (2005) notes, there is a clear link between the Prussian military state and foundational public administrative thought – what Spicer deems the ‘purposive state’: a nation that turns its power, resources, and citizens towards certain ends, as opposed to the state as a ‘civil association.’ Spicer succeeds in showing the influence of Prussian and German thinking on modern American administration through their influence on Woodrow Wilson and others. 
Dewey was wary of the militarism that he saw in Wilson and others, particularly a warlike mentality and nationalism he felt was ultimately destructive to his normative view of what the American state could be, arguing that (Dewey, 1915, p. 118)

> “…philosophical justification of war follows inevitably from a philosophy of history composed in nationalistic terms. History is the movement, the march of God on earth through time. . . . War is the signally visible occurrence of such a flight of the divine spirit in its onward movement. The idea that friendly intercourse among all the peoples of the earth is a legitimate aim of the human effort is the basic contradiction of such a philosophy.” 

Though Wilson expressed disquiet about Prussian state theory almost thirty years earlier (W. Wilson, 1887), he believed Americans could safeguard against the excesses, that we could borrow effective methods of sharpening a knife without engaging in the same murderous ends. Though foundational, Wilson’s propensity to engage in self-evident truths would be replaced by public administration scholars wary of easy answers based on clever metaphors (Simon, 1946).

The promise of technological solutions was attractive to Progressives as they sought to alleviate class struggle and suffering. The classical public administration born in the pragmatic and Progressive early 20th century was one that embraced scientism. This embrace had the unintended effect of silencing the essential voices of women in early public administration (Feldheim, 2003; Follett, 2016) who ran the settlement houses of the period. Science was understood to be a masculine pursuit, while the human-centered approaches of the “settlement women” were left behind by Progressive men who tired of being slandered as “long-haired men” in emasculated service of “short-haired women” (Stivers, 2002).
Gulick attempted to move beyond Taylor's scientific management, with an effort to more logically divide work. Gulick proposed there are limits to division of work, and that proper coordination among the divisions of labor are necessary: If a subdivision is necessary, so is coordination of that work. Gulick was an early positivist who believed empirical research would be necessary to understand a range of questions, including the proper span of control, or how many laborers a manager could be expected to manage well. He did not approve of multiple commands, but instead urged unity of command. Finally, he was not a technocrat and did not trust experts to stay within their own field: "experts on tap, not on top." In his view, the study of organizations must be approached from both bottom-up and top-down perspectives. Gulick combined his insights into a theory of the proper executive: A chief executive’s job is "PODSCORB" planning, organizing, staffing, directing, coordinating, reporting, budgeting. 

### Behavioralism and Beyond  

The end of World War II brought about the end of orthodox (or classical) public administration, and the beginning of behavioral, empirical public administration (Marini, 2000). The behavioralist bent was not unique to public administration scholarship, and was sweeping across the social sciences broadly. In public administration, behavioralism was simultaneously taking place alongside a new humanistic, values-oriented approach. This section will explore the most visible debate between those two views later in recounting the Simon/Waldo debates (Simon, Drucker, & Waldo, 1952). First, however, I trace how the bureaucratic approach was converted to an organizational one.

The post-WWII period brought new energy to the study of public administration and efforts to diversify its theoretical and empirical study. Gulick’s (1937) bureaucratic approach covered earlier is still alive and well in the practice of public administration, even as its academic study leaves the acronym behind as too simplistic. Even in Gulick’s day, other scholars thought his prescription was unrealistic and too unfocused on the people that make organizations work. Charles Barnard (1938) recognized the importance of individuals and that organizations cannot be well understood without also understanding people. While Gulick focused on the formal lines of command, familiar to us today as ‘organization charts,’ Barnard highlighted the importance of informal organizations. Informal organizations are based on personal rather than joint purposes, and promote uniform states of mind by crystallizing mores and customs. Barnard set out several ways informal and formal organizations are interdependent:  Informal organizations give rise to formal organizations; formal organizations are necessary to any large informal organization; formal organizations make explicit the states of mind developed within the informal organizations; formal organizations in turn also create new informal organizations. Finally, informal organizations are necessary to formal organizations as a means of communication, cohesion, and of protecting the integrity of the individual. 

A sociologist at Columbia University, Robert Merton (1939) stressed how the study of bureaucracy misses the importance of personalities within the bureaucratic structure. Merton saw how bureaucracies infuse the employees with certain rules in order to maximize efficiency, but these rules become the end, instead of a means to the end. Merton saw this tendency in organizations that were soon run over with bureaucratic hurdles (‘red tape’) that hindered efficiency and effectiveness. Merton called on other social scientists to begin studying public administration. Many soon did, and relied on Maslow’s hierarchy of needs as a basis for understanding human motivation in organizations. Also at Columbia University, Maslow (1943) described a basic structure of human needs, arranged in a hierarchy: Basic needs, safety needs, love needs, and self-actualization. Though not substantiated empirically, Maslow’s hierarchy proved crucial to the beginnings of motivational and human-focused theories in the study of administration.

The human focus for some public administration scholars can be seen in MacGregor (1960) and his ‘Theory X’ and ‘Theory Y” approach to motivating employees. Most theories of public administration were based on expectations that employees would shirk their responsibilities and therefore needed close supervision and clear punishments to keep them in line. MacGregor saw that another approach, based on Maslow’s hierarchy of needs (Maslow, 1943), was better suited to the evolving workplace. In this ‘Theory Y,’ MacGregor advocated that the individual worker is creative and driven, and a good manager encourages employees to problem-solve on their own, gives them the tools to do so, and then gets out of the way. Theory Y is ‘management by objectives’ rather than the ‘carrot and stick’ management of Theory X. MacGregor saw this as a necessary adjustment to an evolving workforce that expected more out of work than mindless micromanagement: “This is a process primarily of creating opportunities, releasing potential, removing obstacles, encouraging growth, providing guidance.” In MacGregor’s view, this was not leadership for public managers, but management for both public and private agencies. 
By the end of the 1960s, it was clear that the classic model of ideal bureaucracy (Weber, 1947) was no longer serving public organizations well. Unstable political and strategic environments meant that the nature of public organizations had to be more flexible than the strict hierarchical models of the classical theories permitted (D. Katz & Kahn, 1978). James Thompson (1967) theorized on how modern organizations could adapt, with a theory of contingency. Similar to the impact that Lipsky (1983) would have with his street-level bureaucrats, Thompson was influential in raising the profile of middle management in particular. Managers in public organizations must “emphasize change, adaptation, and evolution…adopt an open-systems perspective…anticipate trends, scan for threats, span boundaries, enact changes…and expand the organizations domain” (Morgan, Green, Shinn, & Robinson, 2013, p. 184; Thompson, 1967). Thompson’s model was not restricted to, or even primarily focused on, just public organizations. His work enveloped both private and private spheres, and as was common at the time, did not necessarily differentiate between the two.

### Divorcing Public from Private, Proverbs from Positivism

The application of business principles to public administration practice was a taken-for-granted “good” in public administration , and even today there are consistent efforts to imbue government with the magical efficiency of public markets. One early effort to separate public and private management, and to more closely intertwine democracy and public administration, was made in the book Government is Different (Appleby, 1945). Three aspects differentiate running a government versus a business. First, the government has a vastly expanded scope and impact. Second, the government is publicly accountable to everyone, not just a small pool of shareh0lders. Third, the political character of public administration means that the government must take into account the will and wishes of the people, a factor that recounts Washington’s founding principle of public administration. Appleby saw that government, in its people, attitude, and function, is different from any other activity, including business. He was especially critical of those who would come from the business world and expect governing to be a good fit for them: "Only a politician can be president." Government is different because government is politics, and while businesses are able to select their market carefully, ‘government’ has no clearly delineated border: "Statecraft - government - is different than all other professions because it is broader than anything else in the field of action." 

As late as 1955, with the publication of the first public administration textbook, business and public administration were still seen as somewhat synonymous, and the textbook called for a public administration that is more than “the time-honored approach of ‘muddling through’” (White, 1955). Public administration was seen as the great problem of government, and like the original call for more exacting study (Wilson, 1887), White (1955) suggested that American democracy could learn better administration techniques from the autocrats in Europe. There was a growing focus on the longest-lived organizations, churches and universities (Downs, 1967), and Europe was home to the oldest of both (at least to the Western-centric scholars of public administration at the time). 

Even as Downs theorized the lifecycle of bureaus resulted in highly conservative institutions, however, the landscape of American public administration was shifting. Civil service unions were gaining power as their membership grew massively at both the federal and state level (Mosher, 1968). Bureaucrats were no longer the ‘heroes’ of the progressive era and a new, negative connotation was taking hold. The unending cycle of reform in American public administration (Kaufman, 1969) was due to the uniqueness of the American experience, especially the constitutional nature of power separation that led to a succession of shifts in focus on three core values: representativeness, politically neutral competence, and executive leadership. Kaufman argued from a pluralist perspective and saw that none of the three was ever truly absent from the American consciousness, but the focus changed. And as the focus changed, pressure from groups interested in the other two brought pressure and calls for more reform. Kaufman saw the calls for decentralization of government power in his time as the result of racial and youth power groups who felt underrepresented in the current regime. The constant reform was not a negative, however, as Kaufman wrote that “wheels turning on their own axes still advance.” 

The dangers of too much political control of the bureaucracy became clear in the wake of the Watergate era. In Mosher’s (1974) view, Watergate was an aberration, and extension, and a culmination of events that had their root in a lack of bureaucratic independence. The overwhelming drive to re-elect Nixon subsumed all other ethical and legal considerations for many in the administrative agencies. There was a purge of top-level officials following Nixon’s first term, where anyone deemed too hesitant or lacking pure loyalty was removed. The Watergate climate was the result of too close a relationship between the political and administrative spheres, with the political side pressuring the administrative side to take action designed solely to enlarge presidential power.

#### Simon and Waldo Debates

The most critical inflection point in the modern study of public administration came from Herbert Simon. Simon was an organizational theorist who urged scholars to think carefully about what a methodology of  public administration should be (Simon, 1946): How do we acquire scientific or empirical knowledge about public organizations? Weber's (1946, 2015) ideal bureaucracy does not exist in the real world, so how can we compare and contrast the types of bureaucracy in a scientific sense? Herbert’s wide-ranging critique of the study of administration was born from the positivist and post-positivist debates (Popper, 1959) that sought to replace the verifiability claims of empiricists with a demand for falsifiability. Herbert likened what came before to "proverbs, not science…Armchair philosophizing about administration...has gone about as far as it can profitably go in this particular direction." Herbert provided the push to turn the study of public administration towards post-positivist science.

Dwight Waldo disagreed with Simon’s positivist prescription for the direction of public administration scholarship going forward, and the two engaged in an exchange of ideas in the pages of the American Journal of Political Science. The Simon-Waldo debate was structured on two differing philosophical perspectives that continue to define the study of public administration today (Harmon, 1989). The debate was quite ugly, and a full understanding of the importance of the debate only became clearer with the passage of time, and as Herbert’s unique genius became even more noticed with the awarding of the Nobel Prize in Economics in 1978 (March, 1978). However, two decades earlier the first punch in the defining debate in public administration scholarship began with the fortieth footnote in Waldo’s essay “Development of Theory of Democratic Administration.” Waldo maintains that to follow arguments for efficiency in administration to their logical ends is to engage in ‘nihilism,’ and then while he emphasizes the need for democratic values in making administrative decisions, he manages to slight Simon’s accomplishments as being unscientific  (Waldo, 1952, p. 97):

> “In this contention, the present ‘weight of authority’ is against me. But I believe that there is no realm of ‘factual decisions’ from which values are excluded. To decide is to choose between alternatives; to choose between alternatives is to introduce values. Herbert Simon has patently made outstanding contributions to administrative study. These contributions have been made, however, when he has worked free of the methodology he has asserted.”

Until this point, Waldo and Simon had been complimentary of one another, and both attacked the naïve scientism that had dominated the study of administration to that point. However, beginning with Waldo’s salvo, it was clear that two competing visions had emerged. On the one hand, Simon drew analytic distinctions between facts and values, and then another distinction between administration and policy. On the opposing hand, Waldo insisted that administration and policy were both impossible to separate from normative values (Harmon, 1989, p. 440): “Waldo’s project was, after all, to warn of the limits of science in human – and, in particular, administrative affairs, while Simon’s was to inform us of its power.” Where Herbert sought efficiency, Waldo asked “efficiency for *whom*?”

Many a barrel of ink has been spilled evaluating the Simon/Waldo debates, and it is outside the scope of this essay to cover the differences in full, nor is it particularly helpful to understand either Simon or Waldo’s philosophical orientation to public administration through a handful of their papers in the early 1950s. Some of the draw of this debate is no more than the dramatic counter-punching and name-calling that took place. For instance, consider this exchange opened by Simon in his first reply to Waldo, (Simon et al., 1952, p. 495):

> “Quite apart from whether Mr. Waldo’s premises are right or wrong, I do not see how we can progress in political philosophy if we continue to think and write in the loose, literary, metaphorical style that he and most other political theorists adopt. The standard of unrigor that is tolerated in political theory would not receive a passing grade in the elementary course in logic, Aristothelian or symbolic.”
 
Waldo does not back down from his literary, metaphorical style in responding (Waldo, 1952, p. 501): 
“Professor Simon charges me with profaning the sacred places of Logical Positivism, and I am afraid I have. I use this figure of speech because Professor Simon seems to be that rare individual in our secular age, a man of deep faith. His convictions are monolithic and massive. His toleration of heresy and sin is nil. The Road to Salvation is straight, narrow, one-way, and privately-owned. We must humbly confess our sins, accept the Word, be washed pure in the Blood of Carnap and Ayer. Then, he says, we will no longer be ‘enemies.’”

I do not mean to suggest the two did not engage with the substantive issues that had brought them to loggerheads in the first place. However, the visceral, pointed debates were more fun to read because of the high personal stakes each was willing to bring to bear in defense of their philosophical orientations. This was not a removed, dry, and academic debate most were used to in the low-stakes philosophical battles waged in the pages of American Journal of Political Science. A stylistic dichotomy has persisted in how we think about the Simon/Waldo debate, however, and that differing view is that Simon has come to represent the unrepentant logical positivist, while Waldo plays the foil as the artistic, normative, and value-concerned philosopher. Neither caricature is accurate, but both are helpful in understanding the men’s  influence on the ensuing development of public administration scholarship into a ‘post-normal’ field of inquiry (Riccucci, 2010).

### The New Public (Administration, Management, Governance) 

The logical positivism of Simon and the values orientation of Waldo have been replicated in contemporary conflicts between the two main theoretical orientations of scholars: New Public Management (NPM) and New Public Governance (NPG). Simon’s scientific, efficiency-centered outlook underpinned the rise of NPM to a dominant approach by the 1980s, while Waldo’s vision is seen in NPG, which “makes value conflicts a legitimate function of administrative work” Morgan & Shinn, 2014, p. 9). 

The politics-administration dichotomy is sometimes seen as a quaint or naïve view of the shape of bureaucracy by scholars, but the normative value of a neutral bureaucrat still has a powerful hold on American’s view of the bureaucracy. The traditional views of public administration put forth before the 1970s elevated increased efficiency, economy, and coordination as its primary goals. In his essay "Towards a New Public Administration," Frederickson (1971) added social equity (defined as activities designed to enhance the political power and economic well-being of disadvantaged minorities) to the mix. Frederickson was providing an overview of the 1968 Minnowbrook Conference, a gathering of public administration scholars in which Dwight Waldo played an important role. 

Minnowbrook attendees sought to define the normative orientation for public administration scholarship by focusing on equity (Frederickson, 1971): "Simply put, new Public administration seeks to change those policies and structures that systematically inhibit social equity." In a departure from the logical positivism of Simon, New Public Administration did not elevate neutrality as a value: public administrators "should be committed to both good management and social equity as values.” The New Public Administration (NPA) framework would return with a fuller theory of public administration eventually in New Public Governance (Morgan & Cook, 2015; Osborne, 2006), but at the time its most apparent contribution was to add equity to the traditional formula of efficiency, effective, and economic management of public agencies. 

Between Minnowbrook’s innovation and its eventual translation to the New Public Governance (NPG) came an intervening acronymic regime of public administration: New Public Management (NPM) (Hood, 1991).  Though acronymically similar to New Public Administration, its goals and emphases are quite different. NPM attempted re-inject the responsive, customer-centric management perspective found in business management into public administration (Mastracci & Guy, 2019). To do so, NPM applied business management techniques such as a focus on customer satisfaction, performance measurement, and competition into the public sector. The approach first emerged in New Zealand but soon found eager practitioners in the United Kingdom and the United States (Hood, 1991; Mastracci, Adams, & Kang, 2019). The values of NPM are rooted in principles of economic markets, and those values mean that decisions are often made with market interests (Stone, 2002), such as cost minimization, profit maximization, and return-on-investment. 

Though the critiques of the approach are manifest and will become evident momentarily, NPM was successful in some areas. The focus on measures of efficiency and effectiveness gave public managers and street-level employees (Lipsky, 1983) the capacity to use their expertise to diagnose and correct operational problems (Ammons & Rivenbark, 2008). NPM also emphasized performance management, and the resulting visibility of performance data broadly increased interest in systems of accountability in government (Barzelay, 1992, 2005; Pandey & Moynihan, 2006; Wholey & Hatry, 1992), as well as the role of selection and motivation of public employees to improve organizational performance (Moynihan & Pandey, 2007). Finally, the emphasis on systems of performance management expanded the array of values that were considered important in public administration to include cost, efficiency, outputs, outcomes, impacts, satisfaction, responsiveness, and quality of life (Morgan & Shinn, 2015). 

Though NPM saw some successes, it cannot overcome two fundamental problems. First is that there is no common denominator that can be applied in a cross-cultural context, and so there is no common basis for comparison (Dickson, BeShears, & Gupta, 2004; Haller, Jowell, & Smith, 2009; Mastracci & Adams, 2019). Relatedly, even the modest expansion of values that can be measured pales in comparison to the values available and vital to the study of public administration: “fairness, equity, protection of rights, and transparency play important roles in determining the legitimacy of political institutions, processes, and outcomes” (Morgan & Shinn, 2015, p. 4). The second shortcoming of NPM is its over-reliance on models of business administration to structure the governance of public institutions. Consider just the American example of public administration, with overlapping spheres of authority and influence at the federal level, to say nothing of the balkanized state and local government, reliance on non-profit entities, and contractual relationships between public and private sectors (Morgan, Green, Shinn, & Robinson, 2013, pp. 115–118).

These critical flaws in classic administration were not overcome by NPM, which in turn led to the founding of NPG. As the failures of NPM became apparent, scholars noted a new approach was needed, one that “acknowledges the existence and likely persistence of ‘third-party government” and that brings “the new tools of public action that are now in widespread use to the center of public and professional attention” (Elliott & Salamon, 2002, p. 8). From that call was born NPG, which begins with acknowledging the pluralist nature of the state (Dahl, 1982), and sees that to manage such a state demands acknowledging the co-production of values among the participants in that state. Co-production, in turn, leads to value conflicts, and it is the role of public administration to manage those value conflicts (Stone, 2002). 

The second main advantage of NPG over NPM is in the former’s focus on an engaged citizenry, enabling the efficiency found in co-production. NPG moves well beyond the limited, dichotomous view of public versus private sectors in the classical public administration to a networked, holistic concept of public and private and non-profit (Pestoff, Brandsen, & Verschuere, 2013). This integrates the polycentric theories of the Ostroms’ work (E. Ostrom, 1982; 2011; V. Ostrom, 1987). The polycentric concept was originated in studies that looked at conflicting studies of municipal police departments (Parks et al., 1981), which could not parse why small city police departments had fewer costs, while they enjoyed more trust and satisfaction from the residents they served when compared to large police agencies. The orthodox theory at the time predicted that the efficiencies of large metropolitan police agencies should improve trust and satisfaction among residents. The answer to the seeming contradiction was found in what was deemed ‘co-production’ of public safety (Parks & Ostrom, 1999). In smaller jurisdictions, residents knew their public safety officials and felt safe reporting suspicious activity and crimes to a degree that residents of large metropolitan areas did not. The close relationship between public and private actors co-produced public safety, and accordingly the costs of public safety were less in smaller jurisdictions. This model of co-production was soon modeled in areas of local governance other than public safety (McGinnis & Ostrom, 2012). Though there were substantial issues with study operationalization and measurement know even at the time (Pachon & Lovrich, 1977), the establishment of co-production as a legitimate theoretical construct in public administration is still important today. Co-production is a core value of NPG, and means that successful public managers are able to interact with a public that is citizen, customer, and partner (Thomas, 2013). 

### Conclusion

Looking back on the first century-and-a-half of the formal study of American public administration, one can quickly see how the field has consistently been drawn to consistent dichotomies. Wilson (1887) saw it as a division between policy and politics. Simon and Waldo drew distinctions between science and values (Harmon, 1989). New Public Management sought the adoption of private market theories into the management of the public weal. New Public Governance pivoted from the business management model of governing and reinvigorated public management with a call to blend public, private, and non-profit. The seduction of epistemic communities continues to drive much of current scholarship as well, as sub-communities of the public administration field hew close to their preferred traditions and methods of uncovering T/truth (Riccucci, 2010). These divisions can undermine how the field advances, as “academic sectarianism produces less understanding rather than more…Epistemologically, we should recognize there are multiple valid and perhaps even complimentary paths to understanding” (Lake, 2011, p. 465). Riccucci (2010) suggests the answer to dogmatism lies in recognizing that the applied nature of public administration means it operates outside the paradigmatic strictures of Kuhn (1970, 1974): maintaining some semblance of methodological pragmatism, matching method to research question, and triangulating on answers with multiple methods.  


## Optional Question 1:

Critics argue that the public policy field has made little theoretical progress, finding itself mired in description and journalistic analysis. Critique this assessment, evaluating the extent to which the major theoretical approaches to the study of public policy meet the standards for theory. Identify competing theoretical frameworks and their chief proponents, discuss their contributions and limitations, and suggest what is needed for them to make the transition from framework to theory. 

### Policy Theories are Scientific Theories

In the early 2000s a new policy theory entered the scholarship – the Narrative Policy Framework (NPF), which centered the power of policy stories to shape policy outcomes. In response, Paul Sabatier, a leading policy theorist, pushed the originators to be “clear enough to be wrong” (Shanahan, Jones, & McBeth, 2018, p. 332). To that end and “inspired by postmodernism and the seemingly contradictory charter of science” (Jones, 2018, p. 724), NPF aimed to produce work that could stand up to this Popperian critique (Popper, 1959). By 2010, the NPF was formalized as a “structural account of narrative” which sought to “test the influence of policy narratives on policy processes, designs, and outcomes at three different levels of analysis” (McBeth et al., 2014, p. 227). By 2013 the Policy Studies Journal held an NPF focused symposium featuring tests of the framework, and in 2014 the NPF held its place in the third edition of an influential textbook, Theories of the Policy Process (McBeth et al., 2014; Sabatier & Weible, 2014). To complete the story arc, in 2019 the academic journal Policy Studies named a leading NPF theorist, Michael Jones, to the editor-in-chief position.
The historical context above is important in that it helps illustrate how the NPF was born from post-positivist instincts but adopted to the positivist, falsifiable demands of the policy process academy. Proponents of NPF argue that the admixture of positivist/post-positivist scholarship renders critical discourse studies and other poststructuralist concepts normally “outside the realm of empirical study” (Jones & McBeth, 2010, p. 329) into a scientific approach “clear enough to be wrong” (Shanahan et al., 2018, p. 332). The early critique of ‘unscientific’ is not unique to the NPF. A common critique of, and within, policy theories is that they are not really scientific enough, more akin to journalism than social science. This historical tendency has led to a sensitivity within the policy process research world, and as a result, the field demands much of itself and potential new theoretical frameworks. This essay will defend the scientific credentials of the public policy theory scholarship, by focusing on the underlying theoretical frameworks that motivate the vast majority of research in the area. 
This essay will cover five main theoretic approaches to public policy and is structured to move somewhat temporally as well. It begins with a quick acknowledgment  of the theory of the linear policy process. Following the rejection of the assumptions of the linear process (Cohen, March, & Olsen, 1972) came punctuated equilibrium (PE) theory, which still retained some linear elements but moved away from the incrementalist predictions of the linear theory.  The third theory, multiple streams analysis (MSA) helped explain the significant policy shifts in punctuated equilibrium theory but added theoretical flexibility, which gave it greater explanatory power for understanding why some policies are adopted, while others lay fallow. While MSA has proven popular for its parsimony and flexibility, some scholars have long complained it lacks the ability to explain policy process in the many different contexts in which policy is found. The fourth theory, advocacy coalition framework (ACF), takes many concepts from the MSA framework but trades parsimony for greater explanatory power. The final section of the essay closes with a synopsis of social construction of target populations (SCTP) theory. SCTP does not attempt to explain everything in the policy process but instead deconstructs the language (Wittgenstein, 2013) and assumptions of policy actors, which then are used to justify actions that have inequitable consequences for different populations affected by the policy. In closing, the essay points to the importance of scientific theory in policy studies, and to the importance of the scientists in the area to remain pragmatic and flexible to the constantly shifting policies they aim to study.

### The Linear Policy Process

The development of non-linear policy process theory is a relatively recent development, and the linear process model remains the most common way of thinking about how policy is developed outside policy studies. The linear policy process is the natural outgrowth of applying the most simplistic rational choice assumptions to policy. In policy studies, the theories that come after the linear process, and its assumptions, are often reacting to it. 
Linear policy process theory makes assumptions that are rooted in rational choice assumptions. People are self-interested beings who have ordered preferences (preferring one option over another), and those preferences are stable. The individual has no mental, emotional, or cognitive deficiencies, which would hamper their ability to make choices in their own best interest. It assumes that the individual is capable of knowing all information related to the choice before them, and thus is able to make a reasoned decision about which option to select, with the predicted choice being the one which maximizes the individual’s benefit while minimizing the cost. These assumptions have been set aside as unrealistic models of human behavior in modern political and policy scholarship (Green & Shapiro, 1996; Jones, 2002)
The linear process was never useful as a predictive model of policymaking. The Garbage Can Model of policy (Cohen et al., 1972) takes the opposite assumptions and successfully challenged rational choice as an appropriate set of assumptions for policy theorists. The Garbage Can model explains the policy process as inherently chaotic and unpredictable, a mix of problems, ideas, technology, and solutions, all flowing around in an amorphous soup, from which a policy eventually congeals when the right components interact with one another. While Garbage Can modeling has not proven useful as a theoretical framework in the long-run, it is influential for the theories it inspired, particularly multiple streams analysis (Kingdon, 1995; Zahariadis, 2014) and the advocacy coalition framework (Sabatier & Weible, 2007).

### Punctuated Equilibrium

Punctuated equilibrium (PE) (Baumgartner & Jones, 2009; True, Jones, & Baumgartner, 1999) is a policy theory which borrows from biological science to describe long periods of policy status quo, suddenly interrupted by significant shifts in the policy landscape. Baumgartner and Jones recognized that the slow incremental policy changes predicted by the base linear policy model were not reflected in the empirical policy evidence. Rather than slow, steady policy progress, they saw long periods of policy stability, which were then suddenly disrupted by sharp changes in short periods of instability. This, to the authors, seemed to reflect the sudden evolutionary adaptations seen in the biological sciences, as species maintain long periods of stability, with sudden natural adaptations (Gersick, 1991; Gould & Eldredge, 1977). 
Though more useful than its simplistic predecessor, PE is still at its root a theory of linear change, though with generally more relaxed assumptions about the rational nature of the individuals involved. For instance, PE assumes that people are boundedly rational (Simon, 1976) rather than perfectly so. Similarly, PE recognizes that policymakers have limited attention capacity, and cannot know everything about a policy issue. Another critical concept in PE is that of framing (Chong & Druckman, 2007; Zaller, 1991, 1992), which groups use to define how a policy problem is understood, in order to better position their preferred policy solution. Similar to both multiple streams theory and advocacy coalition framework (covered later), the PE framework attempts to understand how policy groups operate to bring about policy change. PE uses concepts such as agenda-setting, policy monopolies, and venue shopping to explain how these groups overcome the natural tendency towards stability and continuity in the policy environment. With agenda setting, groups make strategic choices about how much attention to bring to their preferred policy solutions. If they worry that attention will risk derailing the policy they will work to minimize attention, while at other times, mainly with lawmakers reluctant to pay attention, the policy groups actively manage attention around a policy problem and solution in order to generate political momentum. 
Policy monopolies, which are reminiscent of the ‘iron triangles’ of earlier policy studies (Jordan, 1981) develop in specific policy areas, and like in the advocacy coalition framework (Sabatier & Weible, 2014), these monopolies can persist for long periods of time, as they work to continue passing policy which reinforces their access to resources and thus policy influence. The answer to policy groups that are locked out of a policy monopoly is what Baumgartner and Jones (2009) refer to as ‘venue shopping.’ If a group is locked out of the legislative policy arena, for instance, they may choose to change venues and begin looking for ways to pass their preferred policies at the executive or judicial levels of government.
Punctuated equilibrium policy theory was developed in the United States, and it provided a useful explanation of empirical policy changes there. Early use of PE theory (Baumgartner & Jones, 1993; 2010) was used to explain US nuclear policy, which existed mostly out of public sight in the post-war period. Following decades of that stability, where the policy was primarily left to technical experts and legislative subcommittees, anti-nuclear power advocates were successful in challenging the positive image of the nuclear industry, and venue shopped their policy ideas to courts and the public. The existing policy monopoly was broken, and heavy regulation of the nuclear industry effectively halted the expansion that had been seen in the post-WWII period. 
The US government is structured in a divided power arrangement, which tended to reinforce status quo arrangements, and was seen as responsible for the periods of policy stability. However, the PE theory has been usefully applied in non-US contexts as well. A comparative study of policy regimes in the US, Denmark, and Belgium (Baumgartner et al., 2009, p. 615) using data from “dozens of processes across three nations and covering hundreds of thousands of observations” found the same non-normal distribution of policy inputs and effects. This study provides strong evidence that it is not necessarily the US constitutional system that is providing friction in policy development and thus favoring the status quo. While all three countries in the study are democracies, there are enough structural differences to suggest that a “General Punctuation Hypothesis” can be applied in comparative contexts. 
Punctuated equilibrium theory is robust and takes its place alongside multiple streams analysis and advocacy coalition framework as one of the most cited (Baumgartner et al., 2009) and useful modern theories of the policy process. It provides a framework that allows even non-scholars to connect with a relatively simple idea immediately – things tend to stay the same until they do not. At the same time, it has enough complexity and flexibility to be adopted in varied political contexts. 

### Multiple Streams Analysis

The appeal of the linear policy process theory was its one-dimensional, straight path construction of policy development. However, scholars have long recognized that the linear process is far more normative than descriptive. John Kingdon attempted to lay out a more realistic, descriptive model (Kingdon, 1995), in what is known as Multiple Streams Analysis (MSA). On the surface, MSA has similarities to punctuated equilibrium theory (Baumgartner & Jones, 2009), but it does differ in its departure from the linear process assumptions that punctuated equilibrium held. MSA takes the path between the utter chaos of the garbage can and the too-linear punctuated equilibrium frameworks, and in doing so presents a more compelling theoretical structure than either. 
MSA recognizes that policy is complicated, like the social problems it attempts to address. Ambiguity is at the heart of why policy is so difficult to study (Zahariadis, 2014), because policy actors can never really know the root cause of a social problem, and even problem definition – the start of the linear process model – is ultimately a contestable, political step (Schneider & Ingram, 1993). Rather than assume policy actors are purely rational beings, MSA holds that humans are boundedly rational (Simon, 1976), and as such, operate with limited information capacity, selective attention, and imperfect cognition. Further, there are significant time constraints that limit the ability of policymakers ever to know ‘enough,’ let alone grok all the facts that perfect decision making would require. In the end, MSA seeks to answer the question: In a universe of nearly limitless policy problems and solutions, how do the relatively few new policies rise above the rest?
MSA is one of the most cited academic theories of the policy process and “key influence on the study of public policy” (Cairney & Jones, 2016, p. 1) with over 12,000 citations as of 2015. The appeal of Kingdon’s framework lies in its flexibility. MSA posits three ‘streams’ in the policy process – the problem, political, and policy streams. How these three streams come together (or fail to) is a useful metaphor for thinking about why specific policies are implemented, while other, similarly good policies, fail. Understanding the three streams is key to understanding MSA. While the streams are discussed in a certain order here (problem/political/policy), in practice, the analysis is much more about how the streams interact than about their temporal order. 
In the problem stream, attention is paid to how attention is gathered around a policy problem. “Attention” in this frame can be mean many things, none of which are necessarily objective indicators. Attention might be statistical information that points to a problem, or in some cases, a crisis gathers immediate and widespread attention to a problem. Problems exist whether or not attention is being paid to them, and MSA recognizes that policymakers are only ever paying attention to a tiny subset within the universe of problems that they could be minding. 
The political stream refers to the many people, advocacy groups, and political bodies who are interested and involved in policymaking. The partisan composition of a US Congress, for example, will have an impact on whether or not a policy solution that is perceived as increasing tax burdens has any chance of being implemented. Similarly, the national mood in the wake of a financial crisis must be considered when considering whether complex regulatory policy might be implemented. The political stream is about the actors who must pay attention to a problem, and possible solutions, before a policy can be implemented. During some time periods, the political stream dictates that some problems in the problem stream will not gather attention, while ideas from the policy stream will not be considered. In the US context, periods of divided government, when one party controls Congress while the other party controls the presidency, are predicted to have relatively little policy movement, though recent scholarship convincingly disputes this prediction (Lee, 2009, 2016). Conversely, periods where one-party controls both the executive and legislative functions are predicted to have a better chance of implementing larger policy changes. 
The policy stream is described as a policy ‘primeval soup’ by Kingdon, where potential policy ideas from a variety of policy actors conceive of potential policy ideas in policy communities. At any point in time, the policy stream contains a large number of possible policy solutions, but not all of them are feasible, supported, or available. While a policy idea may originate with a single actor, the ideas change as they are exposed to and considered by other actors in the policy stream. The ideas that eventually become policy are the result of a large number of participants modifying the original idea, and is often a much broader solution than the original, narrower solution. Some of these actors are so-called ‘policy entrepreneurs’ who recognize an opportunity to insert their own policy solutions into one which is gaining support. 
Policy entrepreneurs are essential to MSA. These are the people and organizations that recognize when the politics and policy streams are not in sync. A policy entrepreneur waits for and recognizes when the two streams offer an opportunity for their preferred policy idea to be implemented. These policy ideas are developed before the actual streams coincide, and the preferred policy is offered as a solution to a problem that has garnered attention. At the same time, these policy entrepreneurs will work to bring the streams together, for example, by attempting to bring more attention to a problem while the politics stream is perceived as favorable to their already developed policy solution. 
Metaphors to think about the stream process in MSA are numerous (Cairney & Zahariadis, 2016), and that flexibility has been key to its success. Some think of the streams as literal rivers, which, once mixed or merged, are challenging to unentangle. Kingdon suggests a space launch metaphor in which all factors must be perfect for ‘launch,’ implying that policy makers will abort a policy before implementation if all the factors in the streams are not ideal. 
MSA assumes that when the problem, policy, and political streams come together, there is an opportunity for policy change, but most of the time the streams are not synchronous. Policy entrepreneurs are thus critical to policy change, as they work to align timing in the streams to create the window of opportunity for their preferred policy change. They work to gather critical mass attention to a problem, so that a solution is demanded. They work with other policy actors in the policy stream to develop their preferred solution to the identified problem. They work to shift the political landscape, so that policy and lawmakers are persuaded to adopt their solution. 
In the end, the flexibility of the MSA metaphor, and the relatively low barrier-to-entry for scholars to understand policy through the MSA framework has made it one of the most popular and useful ways to examine policy (Cairney & Jones, 2016). The ease of use of MSA and the associated limited empirical usefulness will stand in stark contrast to the advocacy coalition framework (Sabatier & Weible, 2007).

### Advocacy Coalition Framework

The advocacy coalition framework (ACF) was developed by Paul Sabatier  and Hank Jenkins-Smith (Sabatier, 1988; Sabatier & Jenkins-Smith, 1993), and from the beginning has been defined by defining the role of belief systems in the policy process, especially their role in shaping policy-oriented learning. The most complex of the mainline policy theories covered in this essay, ACF attempts to develop a holistic theory of policymaking. Because it is designed to be applicable across a variety of policy contexts, and because it assumes that each policy environment is inherently complex, the ACF framework is itself quite involved. 
In the ACF framework, policymaking takes place in a complicated environment that contains multiple actors across multiple levels of government (Weible, Sabatier, & McQueen, 2009). Policymakers have very high levels of uncertainty, and their decisions are always made with inherent ambiguity. Policy decisions take years to produce policy outcomes, and those outcomes are difficult to ascertain with any certainty. ACF recognizes that there are also different types of policies at play, with some policies being fairly straightforward, others being very technical and complex and done outside public notice, while some policies are incredibly political, controversial, and evoke national partisan fights. 
Beliefs are a key concept in ACF, as individuals and coalitions compete in politics to turn their beliefs into implemented policy. In ACF, there are three types of fundamental beliefs. ‘Core’ beliefs are those that are so rooted in the individual that they are unlikely to change or be changed by external events. Core beliefs tend to be so broad that they are unlikely to provide meticulous rules for policy. Conversely, ‘policy core’ beliefs are more likely to be changeable, and more likely to influence how an individual believes policy should be constructed. The third type, ‘secondary aspect beliefs’ are far less important to the definition of the individual and much more likely to shape their views on policy implementation. They are also more easily shaped than the other types of belief through learning new information about a policy. Individuals with shared belief systems are likely to be found together in coalitions, which form ‘policy subsystems’ in ACF analysis.
ACF treats policy subsystems as the unit of analysis. These subsystems are comprised of politicians, policy experts, advocates, and professionals. These subsystems are similar to the “policy stream” in the multiple streams framework (Kingdon, 1995), and in ACF, the policy subsystem contains coalitions of associated members all focused on a specific policy issue. These coalitions are ‘epistemic communities’ (Haas, 1989) –  systems of shared belief and activity – and networks within the subsystem can cooperate or compete to bring their preferred policy solutions to the forefront during policy debates. Strong coalitions often dominate policy issues for long periods of time, and because ACF is concerned with policy cycles, the periods examined often stretch out a decade or more.  Lawmakers, who are constrained in attention and time, often assign responsibility in a policy area to senior public administrators, who, in turn, rely on the advice and consultation from policy subsystems that are framed as experts in the area. 
Within a policy subsystem, coalitions compete in the policy space. In a simple hypothetical, Coalition “A” and Coalition “B” each have a preferred policy solution. Between the two coalitions is are “policy brokers” who are also part of the policy subsystem and who work between coalitions and lawmakers. Each coalition has its own policy beliefs and resources to compete against the other, and policy brokers help structure that competition. Eventually, a decision is taken by the governmental authority with jurisdiction in the policy space at question. 
The governmental decision has outcomes for new institutional rules (or removal of old rules), new resource allocations, and appointments to new institutional bodies. There are also policy outputs from the policy decision, which in turn lead to policy impacts. The new rules, resources, appointments, outputs, and impacts all exist in a feedback loop, which in turn alters the existing coalition arrangements. In extreme cases, a policy coalition may cease to exist as the winning coalition solidifies itself as the dominant voice in the policy subsystem for years to come. More commonly, there is simply a shifting of resources and policy strategy among the advocacy groups that comprise the coalitions, and the ‘game’ plays on. 
There are factors in the ACF framework outside of the policy subsystem, all of which have effects on the subsystems. There are relatively stable factors, reminiscent of the forces in punctuated equilibrium theory, which serve to produce a policy environment which favors the status quo against change. These stable parameters include the core and policy core beliefs of the policy actors, social values, the distribution of resources, the social structure in which the subsystems exist, and the core structures of the government (i.e. a constitutional democracy versus a communist state). The common theme of the stable factors is they tend to be exogenous to the subsystem and other influencing factors. These stable factors influence the rest of the framework but tend not to be influenced themselves. 
Unlike the relatively stable factors, ACF also recognizes that there are endogenous factors that both significantly alter and are altered by the policy environment; these are events that are reminiscent of the ‘shocks’ in punctuated equilibrium theory. These changes can include systemic changes in the governing coalition of a subsystem, socio-economic changes such as significant financial crises, sudden shifts in public opinion (such as those seen in the last decade on gay rights and marijuana legalization), and finally, decisions in other policy subsystems that substantially impact on the subsystem being analyzed. Rarely, like in punctuated equilibrium theory, these external events can be linked to a huge shift in the policy environment, most likely by providing a shift in the internal environment of the policy subsystem. An example of this can be seen in the policy environments following both World War I (a move towards US isolationism), WWII (a move towards international organizations to prevent widespread war), and the Great Depression (a move towards a social safety net).
Also external to the policy subsystem are the opportunities for long-term coalitions to take advantage of. These opportunities are themselves influenced by the stable factors described earlier, but also directly affect how policy subsystems operate. These factors are related to the political systems in which policies are considered, such as the difference between divided party control of the executive and legislative branches of the US government. These factors will dictate whether, and how much, consensus is needed before a policy can be adopted. In broadly democratic political systems, the amount of consensus is relatively high compared to systems with politics that allow for a single governmental actor to take drastic policy action. 
The final structure in ACF theory to be considered are the short-term constraints in which policy subsystem actors operate. These constraints are affected by both the opportunities factors and the external events, but the constraints also operate directly upon the policy subsystem as well. For example, in a policy environment where there has recently been significant policy shifts, the coalitions within a policy subsystem are all constrained from further action as law makers turn their attention to other policy subsystems. 
ACF theory is considered to be the creation initially of Paul Sabatier, but upon his passing, the theory has been continuously refined and adapted to the policy realities of the different contexts within which it continues to be applied. ACF has proven resilient, as it maintains the theoretical flexibility of the theory systems that preceded it while recognizing the feedback loops (Soss & Schram, 2007) that incorporate the influence of stability, shocks, constraints, and opportunities in the policy and political systems. The drawback of ACF theory is that it remains a difficult proposition to translate effectively for non-academic audiences, whereas multiple streams analysis and punctuated equilibrium theory both benefit from the ability to construct easily understood metaphors around policy problems and proposals. 
Recent work linking the streams framework of MSA with the stages analysis of the advocacy coalition framework (Howlett, McConnell, & Perl, 2017) shows a path forward for researchers who want a more robust system for analyzing policy, particularly in the comparative policy literature. Howlett and his colleagues formulate a five-stream framework, adding a program stream and a process stream, all of which proceed together along the traditional linear policy stage path. Though too soon to judge whether such a combined model will prove any more useful in both theoretical and empirical contexts – and it must, given the additional complexity the model has compared to more parsimonious models – there is at least an attempt to synthesize the main policy theories, most of which are at least several decades old. 

### Social Construction of Target Populations

To this point, this essay has concentrated on the most extensive theories and frameworks, which all aim to explain the policy process as a whole. This proves to be a challenging goal for policy theory to meet, given the extreme complexity in policy types, political environments, and policy problems. However, not all theory must be so comprehensive, and in some ways theories with more restricted aims, like the social construction of target populations (SCTP), are more able to give clear theoretical explanations because they examine smaller pieces of the broader policy environment. 
SCTP was first developed by Schneider and Ingram (1993) and defeats another assumption of the linear process – that policymakers, or policy itself, are neutral or unbiased actors. Their argument is not itself post-modern but builds on post-modernist critiques of language, which deconstruct the power relationships inherent in language (Foucault, 1991, 2005; Yanow, 2003). Foucauldian discourse analysis has been effectively used by researchers to understand how different approaches to language “contain critical assumptions about how changes in policy relate to broader social change” (Sharp & Richardson, 2001, p. 193). The central role of language in policy debates (Schmidt, 2000) reflects how important language is to the human experience more generally: “The limits of my language mean the limits of my world,” (Wittgenstein, 2013, pt. 5.6)
Schneider and Ingram show that elected policymakers adopt value judgments about the social groups which are impacted by policy programs and that those value judgments have an impact on the policies they create and implement. In this framing of political statements, some politicians will, for instance, use language that implies individuals living in poverty are lazy and have created their own bad situation. This framing can justify policies that withhold government benefits from the targeted group. But just as language can justify under-benefitting certain social classes, it can also over-benefit others. The same politician may use language which confers noble, worthy qualities on business owners, which would then serve to justify policies that shift resources to that social class. Moreover, this type of construction is not limited only to politicians, and front-line, street-level bureaucrats (Lipsky, 1983). Police officers and teachers  have been found to construct their own identities of the citizens they serve, sometimes to the detriment of those citizens (Maynard-Moody, Musheno, & Musheno, 2003)
Construction of target populations is not as simple as ‘positive’ and ‘negative’ populations, however, and Schneider and Ingram illustrate this point (1993, p. 336) through their use of a two-axis notional figure, where measures of ‘positive’ and ‘negative’ constructions are paired with ‘high’ and ‘low’ perceived power constructions. Power in this use is the ability of a social group to accept or reject the image painted onto them. This gives a four-category scheme of ‘advantaged’ (high power/positive), ‘contenders’ (high power/negative), ‘dependents’ (low power/positive), and ‘deviants’ (low power/negative) social groups. 
These simplistic categorizations of complex populations make it easier to see how politicians and governments implement policies that over-benefit the advantaged while making it extremely difficult for ‘deviant’ populations to even challenge their disadvantaged status in policy debates. This creates a policy feedback loop (Larsen, 2018; Pierson, 2000), as an advantaged group like homeowners not only are over-benefitted in terms of resources granted by policy, but then are able to reify their position in the social hierarchy, leading to more opportunity to implement even more policies that will benefit them. This creates asymmetries of participation and power, and those asymmetries are reinforced by the system creating and accepting social constructions of the deserving and undeserving. This flaw in the system has long been recognized in political studies (Schattschneider, 1960; Schlozman, 1984; Stone, 2002), but SCTP offers a useful empirical starting point for understanding how particular social groups have been affected by policy choices influenced by social construction. 
One of the most potent critiques offered by SCTP is showing how these constructed beliefs about social classes not only have immediate effects on resource allocation but have effects on those social classes long after the policymaker has left office. This phenomenon is known as a feed-forward effect, or in other literature as path dependence (Pierson, 2000). Path dependence recognizes that the timing of policy choices matters, and policymakers select policies that have self-reinforcing feedback processes (Soss & Schram, 2007). These processes represent the resiliency of institutions that are far longer-lived than the policymakers' tenure (Sanders, 2006). Path dependency imposes a cost on going ‘back’ to a previous point. The longer a policy scheme has lived, the higher the cost. In this way, earlier choices have a more significant impact than later ones, as the policies themselves shape the institutions that house the policies (Mettler, 2002). 
SCTP offers a compelling critique of policy studies itself, as it uncovers how the language involved in policy can compel certain beliefs and narratives that hinder, harm, or help certain classes of individuals (Sharp & Richardson, 2001), even as policy scholars unthinkingly use the same language. Further, SCTP critiques the underlying, formative ideals of early public administration and political science, that of the neutral and unbiased bureaucrat, or public administration scholar.  From the founding of the American political system, the ideal of competing factions balancing the power of any one faction (Dahl, 1982; Madison, 1787) has provided a compelling argument that the US constitution and division of power among the federal branches would protect minority interests from the powerful machinations of the majority. However, the justifications of the pluralist federalist system were largely imputed by Madison and Hamilton into the Federalist Papers in a post-hoc manner intended to justify the ratification of the US Constitution (Peterson, 2012). So, rather than the administrative and policy state providing an intricate balancing wheel (Madison, 1787; Rohr, 1986) against the predations of a majority, at least in some cases SCTP theory allows us to see how policy and lawmakers are able to use the concealed power of language to prolong and protect the interests of the already powerful.
One limit of SCTP is that it is less concerned with comprehensive theoretical explanations of the policy process, and so in cases where there are not clear-cut social classes at play, SCTP may be less useful. A second limit is that, at least in the original construction of the theory, there is little said about how social classes might contest how they’ve been constructed by policy makers and the public. SCTP has little to say about how, or more importantly why, one social group may attempt to help challenge the social construction of a less powerful one. Why, for instance, would a feminist group – hypothetically located as a ‘challenger’ in SCTP – want to help restore the voting rights of an ex-prisoner class? SCTP still has buried assumptions of rational choice, presenting the actions of the powerful as merely, or purely, self-interested.  A final limit of early SCTP theory was a lack of direction – what should individuals and advocates do with this knowledge. That critique has been substantially, though not wholly, blunted as more researchers have become interested in critical policy theories ( Jones & McBeth, 2010; McBeth, Jones, & Shanahan, 2014). Recent work has extended the original insights of SCTP by examining the ill effects of economic policy concentrated on women and blacks (Andersen, 2001), food justice (Billings & Cabbil, 2011), and Native American school children (Quijada Cerecer, 2013).

### Conclusion

Policy studies are clearly much more than mere journalism. To engage properly with policy studies requires a canvassing of many complex policy process theories, and understanding both what they are capable of answering as well as what research questions they are not well equipped to address. This essay has covered only five of the theories available, with an eye towards selecting those that have survived at least several decades of empirical testing. There are more approaches available, and more continue to be added even as the most established theories continue to be honed in the pages of academic journals every month. 
Good theory is portable – it can be carried across contexts, and when “contexts differ…theory is required to generalize from one to another” (Coppock, 2018, p. 11). Kingdon’s (1995) multiple streams framework allows for the identification of  universal concepts (Cairney & Jones, 2016) that can be applied in multiple contexts. Presently, the advocacy coalition framework is still the most flexible and explanatory theory available, and though far from perfect, allows for a broad examination of policy in many contexts. The adaptability of the ACF framework means it can fold in even critical theory insights, which by themselves do not produce an entirely satisfactory explanation of how policy is conceived, adopted, and implemented. 
This essay has strived to make clear that attempts to delegitimize policy studies as journalistic, unscientific, or unfalsifiable are misguided. The policy theory landscape is vast, active, and offers a compelling host of approaches to studying policy problems, proposals, and outcomes. There is no single best theory, though every scholar is likely to be drawn to one or two that fit their skills and interests. More important is to remain methodologically and theoretically pragmatic rather than programmatic (Riccucci, 2010). As policy itself evolves, so must the tools that we bring to the study of it. An excellent example of such reactivity is the Narrative Policy Framework (Jones, 2018), which moves from the axiomatic – stories count in the policy process – to the scientific – how do we count stories in the policy process? But NPF is not the end of policy history, and the policy process theories covered in this final essay are all representative of active scientific communities that investigate public policy. The best evidence that policy theories are scientific is the willingness of the scholars within it to continue to look for better scientific methods to improve our understanding of the many facets of public policy.

## Optional Question 2:

> How would you characterize the state of research in public administration as it has progressed thus far? In what areas has research made the most progress, and in what areas is progress still at the fledgling stage? What are the major questions that should occupy public administration and management researchers over the next 20 years? Why? 

### Ethical Street Bureaucrats and Amoral Artificial Intelligences: Research Past and Future in Public Administration

This essay will begin with a review of two areas that public administration scholarship has made significant progress and one large subject area that is in need of focused and sustained scholarship. First, the elevation of the ‘street-level bureaucrat’ (Lipsky, 1983), and the ethical dilemmas found in public service (O’Leary, 2013), are briefly reviewed. In the second section, the essay develops an argument for the need for sustained public administration scholarship to address threats to democratic governance from developments in big data and machine learning algorithms.

### Street-Level Bureaucracy
Public administration is distinct from mere public policy; as Woodrow Wilson(1887) noted, “Administration is...government in action.” However, action does not come from policy prescription, and even the best policy ideas will founder on the shoals of bad implementation (Pressman & Wildavsky, 1984). Governance comes alive in the hands of the public servants who work at the closest level to the people that policy intends to serve. These public servants are whom Lipksy (1983) deemed “street-level bureaucrats.” Lipsky defines these critical employees as “Public service workers who interact directly with citizens in the course of their jobs, and who have substantial discretion in the execution of their work.”
Lipsky’s theory is critical to the idea of government in action and inaction, especially as it relates to mid-level managers. As these managers move towards greater responsibility in their respective agencies, there is also a danger their collective attention will necessarily turn towards broad policy and idea formation. However, as Lipsky makes clear, by re-focusing on street-level bureaucrats, public administration practitioners enhance service to the poorest citizens, and also through better budgetary management.
Lipsky’s theory brought a renewed focus on how to implement the equity goals of the New Public Administration formulated at the Minnowbrook gathering (Frederickson, 1971) because he saw how the influence of street-level discretion grew stronger as the public client grew poorer. The managerial focus on efficiency has historically resulted in social inequity among minority groups. To do otherwise disproportionately affects the poor negatively. The poor are forced to seek those benefits from the government, which they are unable to afford in the private sector, and as the “provider of last resort,” the government will be judged by its ability to serve that population. Prior to Lipsky’s most famous work, H. George Frederickson (1971) was calling for scholars to add ‘social equity’ to the primary values of effectiveness, efficiency, and economy in public administration. Frederickson argues that social inequity “constitutes a fundamental, if long-range, threat to the viability of this or any political system” and  concludes, “[I]t appears that new Public Administration is an alignment with good, or possibly God.”
One synthesis of Lipsky and Frederickson is seeing the discretionary powers of street-level bureaucrats as increasing social equity. After all, as Lipsky (1983) writes, “The poorer people are, the greater the influence street-level bureaucrats tend to have over them.” Yet that optimistic view must be tempered with the reality that discretion is not always a balm for inequity. Because street-level bureaucrats are tasked with impactful discretionary decisions with little direct supervision, they are invisible to managers and thus tricky to correct. Furthermore, policies themselves, which guide administrative discretion, are often intentionally constructed to imbue public services with inequity towards unfavored groups (Schneider & Ingram, 1993).
Police work “entails a tension between the exercise of discretion by officers on the street and the control of that discretion by police organizations” (Engel & Worden, 2003, p. 131). Maynard-Moody and Musheno (2012a) are especially leery of police officers discretion, arguing it is within this discretionary power that social inequity is allowed to propagate: “Racial disparities, then, occur in investigatory stops in which law enforcement personnel are granted substantial legal autonomy and are least subject to administrative oversight.” As noted in other works (Epp, Maynard-Moody, & Haider-Markel, 2014; Maynard-Moody & Musheno, 2012b), the impacts of officer discretion are nuanced. While individual officer behavior is better explained by agency policy and legalistic guidance than by individual attitude and bias (Correll, Hudson, Guillermo, & Ma, 2014; Nix, Campbell, Byers, & Alpert, 2017), the policies themselves can perpetuate inequity, and the juridical bounds may grant so much latitude that they “take on the nature of a farce” (Maynard-Moody & Musheno, 2012b, p. S18). 
These discretionary concerns are present even today. Some scholars suspect that officers will subvert the intended benefit of BWCs through their control of the cameras’ activation, specifically (Kerrison, Cobbina, & Bender, 2018, p. 281) “their ability to turn [the BWC] off or position a partner to block the view finder frame.” Others worry that officers with cynical attitudes towards BWCs because of perceptions that camera footage will be used against them, or negatively impact their professional practices and discretion (Katz, Choate, Ready, & Nuño, 2014) may opt to activate the cameras less (Newell & Greidanus, 2018, p. 4): “officer perceptions and interpretations of the technology may impact how they use it.” However, along with my co-authors, in my analysis of what factors are associated with officers activating their body-worn cameras, I find that job function, not attitudinal or demographic factors, explain most of the variation in activations (Adams, Mastracci, Mourtgos, nd). This finding seems to bolster the view of officers using their discretion wisely and as ‘principled agents’ (Dilulio Jr, 1994).  
Despite the possible adverse outcomes, some discretion is necessary at both the institutional and street level of public administration (Huber & Shipan, 2002; Maynard-Moody & Musheno, 2000). Because it is inevitable and essential, discretion is a critical area of study for public administration. If it were not for Lipsky’s contribution, we would still focus our research attention at the policymaker, rather than widening our scope to include the street-level bureaucrats who actually implement policy every day.

### Ethics in Public Administration

Another area that public administration scholarship has been successful in is in elevating the role of ethics in governance, and reviews of the overall health of this area of research “points to a healthy, robust enterprise” (Menzel, 2015, p. 343). Ethics are important at the elite and elected level of governance, but importantly for an applied field like public administration, there are ethical decisions implicated in the everyday working lives of street-level bureaucrats as well (Balfour, Adams, & Adams, 2014; Finer, 1941; Friedrich, 1940; Lipsky, 1983; Maynard-Moody et al., 2003; O’Leary, 2013; Thompson, 1985). The ethics literature is well-developed, and it is outside the length requirements of this section to cover all the significant works. Instead, I will focus primarily on the work of Rosemary O’Leary in her book The Ethics of Dissent (2013). O’Leary’s work has much to say in our modern era, particularly with the impending impeachment of President Donald Trump following the whistleblower report of an executive branch employee. 
It is tempting to imagine a government bureaucracy in which all decisions are just ones, the policies equitable ones, and the outcomes merely a matter of fiat. Unfortunately, such a paradise does not exist. Our government is, crucially, of the people, and George Washington set the goals of public administration firmly on the will of the people (Cook & Klay, 2015, p. 77). By virtue of being populated by the people, in all their flaws, our government is necessarily going to make flawed decisions, implement flawed policies, and have outcomes that range between problematic and disastrous. In this reality, the expectation that all public servants must always follow all orders is dangerous and conflicts with the very ideals of our American experience. An ethical path in a public administration career is possible, but involves struggling with questions of neutrality and structure (Thompson, 1985). Neutrality is the idea that a bureaucrat must be neutral and simply adopt the behavior expected by his organization – in sum, to obey. The ethic of structure is the idea that only the organization is responsible for bad behavior, not the individuals. Thompson (1985) urges us to reject both ethics of neutrality and structure if we are to have administrative ethics. The rejection of structure is inherent in Lipsky’s (1983) street-level bureaucracy, which takes the responsibility and impact of the individual public servant seriously. The ethic of neutrality is more effectively undermined by examining the most commonly understood institutional case where a duty to obey is paramount – the military.

#### To Obey or Not Obey

The idea that the military is full of robotic ‘yes sirs’ is to misunderstand the military and institutions organized along pseudo-militaristic lines such as policing and firefighting (Caldero, Dailey, & Withrow, 2018; Cowper, 2000). A famous American general of the 20th century, George S. Patten, famously said, “If everybody is thinking alike, then somebody isn’t thinking.” The military thrives on the creativity of its members at every rank. In combat, under fire, facing imminent death – perhaps this is the time for unthinking response to orders. Yet even then, the military recognizes there are higher oaths and responsibilities every soldier has, which supersede the need to follow orders. The Uniform Code of Military Justice (UCMJ, 1956), while making it clear that a service member must follow all legal orders (Articles 90 and 92), also is equally clear that service members have a duty to not follow obviously illegal orders (Reeves & Wallace, 2016): 
“Still, the UCMJ articles make clear that obedience is only required for lawful orders. Patently or manifestly illegal orders impose no duty of obedience on the service member and instead mandate disobedience. In fact, a service member who obeys an illegal order is individually culpable for the crime and cannot later assert ‘following orders’ as a defense.”
In fact, this mandate to disobey illegal orders is the result of, and in response to, far too many atrocities committed by those who were ‘just following orders.’ Both American and international courts have consistently found that there are human rights that are so protected, that to violate them in the pursuit of obedience simply cannot be allowed (Balfour et al., 2014). The My Lai Massacre, the genocides of WWII, and the Abu Ghraib atrocities all have the same lesson: The presumption of obedience, such as that found in articles 90 and 92, cannot be used to justify torture, commit war crimes, or participate in other unconscionable activities. These are examples of the “manifestly illegal orders” contemplated within the UCMJ. And though there are no guarantees against ‘administrative evil’ (Balfour et al., 2014), the ability of the military to recognize when discretion is available to even soldiers in combat shows that an administrative ethic is possible.
As seen, the implied ethic of unfailingly loyal obedience to orders is not even a truth in the most militaristic of settings – the military itself. It follows, then, that to apply that ethic in less structured environments is inappropriate as well. What then is the value of dissent in the American public service? Rosemary O’Leary (2013) covers this question with great depth. O’Leary is not pollyannish regarding dissent – she is not arguing it is always appropriate, or even reasonable, and provides plenty of support for the idea that there is a “potential dark side of guerilla government” (2013, p. 126). However, it is in her willingness to accept the middle ground that she is so convincing (p. 118): “Just as it is difficult to argue that there is not a need for obedience by employees, it is difficult to argue overall that acting on one’s strongly held personal and spiritual beliefs in certain contexts is improper.” 
Most would agree that a public employee is not compelled by duty to obey obviously illegal orders. O’Leary is comfortable in exploring the marginal cases where answers are not so clear, and concludes (p. 110) that “not all guerilla government is created equal” – some dissenters are “a canary in the coalmine” while others are simply “delusional single-issue” fanatics. O’Leary is comfortable in not finding some final, clear answer. She notes that “most cases are not so easy to judge” (p. 110) and that the “tensions inherent in guerilla government will never be resolved” (p. 117). Her doubts are more convincing than the surety of those who suspect a robotic response by public employees. Government needs to be efficient and therefore exerts hierarchical control over employees in order to ensure that efficiency. However, hierarchal control inevitably clashes with the federalist priority on local autonomy (Elazar, 1984; Madison, 1787). As illustrated in the “Nevada Four” case (O’Leary, 2013, pp. 27–41), sprawling federal agencies must rely on employees who are local, and some of those front-line employees will eventually begin to prioritize what they see as crucial over dictates from their bureaucratic superiors in faraway offices, who may have never even been to the areas they are attempting to wrest control over.
While O’Leary does not argue all dissent is right, nor can dissent be so easily dismissed as inherently flawed, or that it does not hold an important place in public governance (Brewer & Selden, 1998). Dissent is itself an American ideal (O’Leary, 2010; Ragosta, 2010; Sunstein, 2003). John Steinbeck (1952) captures this feature of Americana well: 
“And this I believe: that the free, exploring mind of the individual human is the most valuable thing in the world. And this I would fight for: the freedom of the mind to take any direction it wishes, undirected. And this I must fight against: any idea, religion, or government which limits or destroys the individual. This is what I am and what I am about.” 
So long as there is an American government that employs Americans, there will be a need to find ways to include the street-level dissenter in public service. 

### Big Public Data
One of the subjects that public administration scholars will be critical to is the effect of big data, machine learning, and artificial intelligence in public governance, though the field has been relatively slow to react to developments in this area. The voice represented by our scholarship is necessary to surface the realities confronted by the practitioners confronted with overseeing the intersection of the public sector and big data, machine learning, and other technologies. There is no doubt that scholarship needs to be multidisciplinary – international power, regime studies, war theory, genocide, administrative evil, and ethics; every field of scholarship will be impacted. These imaginative visions begin with the adoption of big data technology and machine learning at the municipal level – an adoption that is already occurring (Coglianese & Lehr, 2016, 2018). Machine learning and big data are already used in criminal sentencing, policing strategies, and identification of lethality in domestic violence (Adams, 2019; Ferguson, 2017), among others, all of which fit squarely within traditional domains of public administration scholarship. Public administration offers the natural voice to help guide the ethical considerations and responses to the inhuman, or at least non-human, politics of the future (Agarwal, 2018; Battaglio & Hall, 2018). 
Sara Jordan frames the public-sector impact implicit in a shift towards big data (2014, p. 276): “How ought government protect the public against the use of their data but also protect the public through the use of their data?” If public administration scholars do not direct their energy and interests towards investing the human mind into questions of how big data, machine learning, and artificial intelligence interact with governing, it risks becoming outmoded and irrelevant. Public administration is well situated to offer solutions to these questions due to its strengths in multiple methodological and ontological approaches in the field (Riccucci, 2010). 
In a recent review of literature investigating big data and the public sector, Cecilia Fredriksson and her coauthors reveal the complexity and importance of big data, and the critical importance of scholarship (2017, p. 47): “Governments are central to both creating and managing knowledge.” Gary King, director of the Institute for Quantitative Social Science at Harvard University, is clear in his assessment of the changes that big data and artificial intelligence promise  (Lohr, 2012, p. 1): “It’s a revolution. We’re really just getting underway. But the march of quantification, made possible by enormous new sources of data, will sweep through academia, business, and government.” And as political scientists have noted, revolutions tend to have some bloodletting, at least metaphorically, as scientific revolutions look a lot like political revolutions (Farr, 1995). Public administration, concerned with both government and governance, theory, and practice, should not consider itself safe from the big data revolution; no matter ones’ preferred ‘isms’ (Lake, 2011), it seems an unlikely outcome. Recall, however, King’s assertion of the underlying questions being quantitative ones. Even allowing for rhetorical excess, as large as his claims are, they are not encompassing enough. It is a mistake to see big data, which is essentially a descriptor of quantitative information, as having only quantitative implications. Recent advances have made the sophisticated quantitative analysis of even very large text corpora a manageable task (Mourtgos & Adams, 2019b; Roberts, Stewart, & Tingley, 2014).

#### Algorithmic Impacts on Democratic Ideals: The GPT-2 Natural Language Model
One example of our algorithmic future, and of the need for public adminstration scholarship, can be found in the most recent advances in machine learning predictive text algorithms. The most advanced of these publicly known is the ‘GPT-2’ model. Simultaneously released as a blog post on the OpenAI site (Radford, Wu, Clark, et al., 2019), the scholarly article (Radford, Wu, Child, et al., 2019) announcing the development of the ‘GPT-2’ natural language prediction model will be seen as a turning point in political speech. The GPT-2 model, and the paper announcing it are bound to be turning points in politics, broadly drawn, and more specifically, the political and policy implications of artificial intelligence methods. The authors directly address the political and policy implications of their own technology, stating that along with synthetic audio and so-called ‘deep fake’ videos, “technologies are reducing the cost of generating fake content and waging disinformation campaigns…politicians may want to consider introducing penalties for the misuse of such systems.” 

The authors address their concerns about the potential misuse of such systems by publicly releasing truncated models with a staged strategy. Though the full model has 1.5B (billion) parameters, the authors decided to first release only the 114M (million) parameter model in February 2019; a 344M model in May 2019; and a 774M model in late August 2019. 
Reviewing the technical accomplishments of the GPT-2 language transformer is beyond the scope of this essay. However, it should suffice to note that the algorithm surpasses previous attempts in language prediction models, and in some cases approaches human-level capabilities. The model was trained on over 8 million English-language webpages, with the goal of simply predicting the next word in a sentence. A simple goal, but the output of the algorithm is convincing enough that 83% found it indistinguishable from New York Times articles (Kreps & McCain, 2019).

Scare tactics around technological innovation are nothing new. It is easy enough to claim an algorithm is dangerous to the polity - what does it look like in practice, and why would it be dangerous to democratic structures? Consider the following ‘fake essay introduction’ I generated for the purpose of demonstrating the capability of the GPT-2 774M model. Bolded text is the input I used as a seed (I used the introductory sentence to the required question in this submission, page 1), and what the algorithm generated follows in standard text:

As a discipline, public administration is a study in unresolved, and unresolvable, tensions.  The state of the discipline is in its infancy, but its problems are not yet settled . Some aspects of the discipline have been better understood in the past twenty years than in previous decades. What has emerged is a discipline whose underlying contradictions and tensions are as difficult to resolve as the historical struggles over their solution. This is a discipline in which the basic structures of state power are, and remain, fundamentally ill-defined and ill-regulated. The most recent major challenges to the discipline may be found in China, India, and the United States. These include the expansion of governmental power over private sector actors, the emergence of an increasingly fragmented political economy in many countries, the spread of political and economic elites, and the transformation of the traditional political class into political and economic elites. 
The above text selection was generated today, October 15, 2019, in approximately two minutes at 10:13 a.m. It is not perfect in terms of proving a causal argument, but it is certainly passable in conveying a believable argument, particularly to a non-academic audience. The exact same fake-text generative power is available to anyone who desires it – whether it is undergraduate students eager to avoid working on an essay or contentious state-actors who wish to undermine democracy with fake-news. There is no scalar limit to the process, and it is as easy to generate 200 fake-news stories to post to Facebook as it is to generate one. 
To be clear, I am not arguing that the GPT-2 paper is significant because it is the final word in this type of technology. In fact, the ability to generate large amounts of misinformation that is for all intents and purposes indistinguishable from authentic news will only become easier. Importantly, the example above was generated with a version of GPT-2 that is only approximately half as powerful as the full 1.5B parameter model. This is not the end of fake news and disinformation for political purposes, but the beginning. Russian President Vladimir Putin recently predicted that (Polyakova, 2018, para. 1) “artificial intelligence is the future, not only for Russia, but for all humankind…It comes with colossal opportunities, but also threats that are difficult to predict. Whoever becomes the leader in this sphere will become the ruler of the world.” The American electorate (or at least some substantial portion of it) was misled by foreign powers, including Russian-based organizations, in the 2016 presidential election by the intentional use of memes (Permanent Select Committee on Intelligence, 2019). How will the American polity react to conceivable disinformation generated like the above? If public administration is ultimately concerned with the governance of competing values in a democracy, how should we study the potential undermining of that democracy in the face of withering, algorithmically generated, fake news?
Despite the intent of the GPT-2 team to stage releases of the model so that the unintended effects could be judged, such a strategy inherently relies on the belief that either; 1)  no one else can do the same work, or 2) those who are capable of re-creating the technology would also restrain themselves. Both premises are doubtful, as shown by the full release of “OpenGPT-2” by two graduate students at Brown University (Gokaslan & Cohen, 2019) in a post titled “OpenGPT-2: We Replicated GPT-2 Because You Can Too” the same week the OpenAI authors released the watered-down model. Moreover, in their release of the 774M model, the OpenAI authors note that they have spoken to five groups that had already replicated GPT-2. These are only the groups willing to publicly admit they are developing the capability - what of the Internet Research Agency (IRA), a front for Russian intelligence agencies intent on destabilizing American elections (Permanent Select Committee on Intelligence, 2019)? With an ever more networked citizenry comes increased risk that those networks can be turned against democratic ideals – ideals that are at the heart of public administration (Waldo, 1952, 2017).
A metaphor can be drawn to other historically recent revolutions. If a scholar were to posit that neither the industrial nor internet revolutions were particularly impactful to how public administration is performed and studied, would any reader take them seriously? The industrial revolution, with massive gains to efficiency, was not limited to ‘only’ affecting industry – political, governance, and ethical implications followed. Even the very recent internet revolution, just a few decades old, has wrought social changes in the rise of populism (Bimber, 1998; Chadwick & Howard, 2009), among many other consequences to governing. While a comprehensive review of the changes to polities brought by the industrial and internet revolutions is outside the scope of this paper, it is also unnecessary, if one accepts the simple premise that a similarly situated revolution is underway in the move towards big data, machine learning, and artificial intelligence. These shifts, in turn, bring swings in political priorities, in class struggles, and in institutions. It is this insight that underlines the need for public administration scholarship to bring its varied methodological tools to bear on the issues, to buffer democratic ideals, and to seek every opportunity to engage with other disciplines.
The questions about big data stretch beyond mere quantification, and Sarah Jordan (2014, p. 375) sees the value of public administration’s methodological plurality: “The future of public administration lies in its ethical knowledge work and expertise.” The ethical implications of government use of information technology are “one sketchily researched area” deserving more scholarship (Menzel, 2015, p. 363). Some work is beginning to appear, with research papers and publications in legal journals beginning to address the role of machine learning in administrative agencies (Coglianese & Lehr, 2016), questions about algorithmic ethics and fairness (Ferguson, 2017; Friedler et al., 2019; Joseph, Kearns, Morgenstern, & Roth, 2016), and emerging legal definitions of ‘personhood’ among artificial entities (Karanasiou & Pinotsis, 2017). However, these questions, which are necessarily multi-disciplinary, and despite having the potential for grave impact on the public sector (Battaglio & Hall, 2018; Fredriksson et al., 2017), so far lack the input from public administration scholars that would leverage the strength of our focus on merging the theoretical insights of political science with the realities of practice (Guy, 2003). 
Within the next several decades, deep learning neural networks and artificial intelligence will begin to replace two of the four pillars of what Keohane (2009) identifies as the core functions of political science: descriptive inference and causal inference. Retooling public administration through old ontological debates will not answer the question faced by political scientists in the coming years: what are we for? To reframe Rogers Smith (2015, pp. 366–367): perhaps public administration is not so exceptional and is not alone in facing profound change in how scholarship will be done. Does public administration see itself so fundamentally different in scope and complexity that it can escape what other human-centered fields have already begun to cede core functions to? If machinated intelligence comes to dominate descriptive and causal inference, what public administration scholars should get better at is puzzling (Keohane, 2009, p. 360) – observing what does not fit with theory – and conceptualizing, particularly as it relates to translating scholarly arcana to ordinary usage. We must become better data scientists and qualitative researchers and puzzlers and conceptualizers – all at once. Alongside those, society will be in need of intense scholarly focus on instilling our ethical knowledge work into the machine learning, neural networks, and artificial intelligences that are the future of both governance, and the study of governance. 

### Reflexivity

“There is no theorist more clever than the scholar claiming to have no theory” write the authors of a primer on theories of public administration (Frederickson, Smith, Larimer, & Licari, 2018, p. 3). Though they were gently chiding James Wilson’s  proclamation (1989, pp. xi–xii) that any grand organizational theories would be merely “partial, place- and time-bound insights,” I heed their advice. At this time, I am a scholar in the post-normal mode (Riccucci, 2010), who is primarily interested in the experiences of street-level bureaucrats (Lipsky, 1983). Though I am a methodological pragmatist who is open to many ways of answering research questions, I instinctively reach for post-positivist, testable, falsifiable, and empirical answers in my scholarship. I am a public administration scholar because the field is multi-disciplinary and multi-methodological, as am I. Attempts to constrain the research questions and methods germane to the field are pointless because public administration practices are as old as civilization itself, even if the field of study that constitutes public administration is still young (Frederickson et al., 2018).
To borrow an excellent turn-of-phrase , I work in the prose of Herbert Simon, but read and dream in the poetry of Waldo. Herbert Simon, because I value the clarity that constrained and falsifiable hypotheses bring to value-laden policy discussions and the satisfaction of working within sophisticated statistical frameworks. Dwight Waldo – because the most interesting questions I explore are value-laden: how workplace surveillance on wellbeing and street-level discretion (Adams & Mastracci, 2017, 2019b, 2019a); the effect of street-level prosecutorial discretion on general criminal deterrence (Mourtgos & Adams, 2019a); the alienation wrought by detaching emotional expression and public service (Mastracci & Adams, 2018); the importance of listening to the voices of public servants rather than imposing our own scholarly suppositions (Mourtgos & Adams, 2019b); and the difficulty of squaring public and legal opinion regarding police use-of-force as the values of the two (Stone, 2002) rapidly diverge (Mourtgos & Adams, forthcoming). I cannot bring to bear the post-positivist methodological weapons of Simon without first looking for research targets through the eyes of Waldo and Lipsky.

### Conclusion

Though he is the godfather of the science of artificial intelligence, Herbert Simon was not robotic. At least by the end of his life, Simon writes (Simon, 2019) both about the ‘beautiful’ and ‘true’ – the wonderful and the comprehensible – merging humanity and science. While early Simon works emphasized the quantitative and measurable, he grew to see the ontological divisions as somewhat of an artificial distinction. He was right, and with the benefit of hindsight, we can see that both he and Waldo fought against what can be seen now as a naïve scientism. Bounded rationality was not a line drawn in concrete, beyond which stood the permanently incomprehensible, but one drawn in sand, pushed backward by the winds of science over time.  The movement towards (even bigger) big data, more sophisticated and predictive machine learning algorithms, and general artificial intelligence will continue to push back that line. No perfect rationality may be possible, but the unbounded parcels shrink every day. Some of what is revealed by those winds of progress are terrifying and potentially destructive, while some are illuminating and progress the country forward. In modern co-produced models of governance, public administration scholarship must be tightly focused on helping distinguish between the two.
The changes to the public sector brought about by the artificial intelligence revolution will be vast and complex. That complexity, Simon’s work urges us to understand, is not the same as inexplicable: “Wonderful,” he writes in the opening of one of his final works, “but not incomprehensible” (Simon, 2019, p. 1). Simon may seem an unrepentant positivist for some in public administration who embrace more qualitative methods, or at least a post-normal  methodologic pluralism (Riccucci, 2010). But that represents an unfair, limited view of Simon’s work, who, after all, published for forty-nine years after his 1952 debate with Dwight Waldo in the pages of American Political Science Review (Simon et al., 1952).  A more expansive and forgiving view of Simon can be found in Rorty’s assessment (1982, p. xvi): “It is important to realize that the empirical philosophers – the positivists – were still doing Philosophy.” 
In her address to the Southern Political Association, Mary Guy (2003, p. 651) states: “The field is served best when we remain self-consciously aware of the implications of our models and the information they produce.” This highlighting of the importance of the subjective experience is a timely reminder for the role of future public administration scholars, tasked with approaching a world of governance rapidly changed through greater and greater reliance on big data, machine learning, expert systems, and artificial intelligence. Herbert Simon saw intuition as a hidden thinking process; but in a hypothetical world where a machine intelligence achieved true, human or greater level intelligence, our ability to understand the subjective experience of that intelligence is not guaranteed. The human subjective experience represents the cash value of human ethics, of human inquiry, and of human philosophy. John Adams is still correct: Two decades hence, the best of public administration scholars will be those who remain aware of the human and ethical implications of models and information produced by inhuman (or at least not human) “minds.”  The field of public administration should be prepared to begin this undertaking today – for that is what we will be for tomorrow.
