# Building a Question List for American Politics

In this chapter, I present some of the themes you might encounter across subfields of American Politics and Public Administration, along with potential citation sources to investigate as you prepare. The questions are grouped into potential required questions, and those that I see more often as "optional," or shorter essays.

I suggest you don't read all these until you've taken some time to read up in other sections. Sometimes seeing this large of a list can be overwhelming! But rest assured, each of the questions has a lot of interplay with at least a few other questions, and so the same pre-written technique I suggest can be used to answer many different questions.

## Required Questions

These are the types of questions that generally require the student to demonstrate a broad grasp of the entire subfield, and the main arguments within that field. To some degree, exam graders are often looking for the student to not just cover the biggest controversies and unanswered questions in the field, but to also declare where they stand. For this, I will usually start my outline with a declarative statement, i.e. "I say presidents are fundamentally weak." This is definitely a preference and even personality-driven option, however, so use what works best for your 'voice.'

These questions usually require 6500 words or more to satisfactorily resolve, because they require writing across multiple sub-sub-fields. In many cases, for example, you would need to cover congressional studies, institutionalism, and the Presidency to address questions of how restrained a US President is.

### Presidential Power, Constitutional Theory, Executive Branch Constraints

> Much has been made over the years of the American Constitution’s structure as a mechanism to guard against tyranny.  The Constitutions’ resilience has been touted as an example of excellent institutional design that has made manifest Madison’s theory of separating powers and using each to check the other.  Imagine that the American people elect a president with little respect for this system and for the specific theory of a restrained presidency.  Leaving aside theory, what is the empirical evidence for the ability of the system to resist a president lacking self-restraint?  To what extent does the larger Executive Branch restrain the president’s actions?  Assess the ability to Congress, the courts, political parties, federalism and other institutions to restrain the Chief Executive.  Does Madison’s theory hold up to what we know about modern American government?

### Political Elites and Public Influence; Public opinion and elites; behavior

> American politics plays out among two sets of actors:  political elites and the public.  Thinking about American politics and policymaking as a whole, discuss the relative influence of political elites and the American public.  Does the public drive our national politics and policymaking?  Or do political elites have most of the power in our political system?  Critically evaluate American politics scholarship relevant to these questions.  Be sure to identify which authors and the specific literature are most important to our understanding of this dynamic.

### Is political science relevant?

> An irony of modern political discussion is that political scientists rarely appear as experts on American politics in the media, where they are far outnumbered by journalists, professional pundits, and political operatives.  Make the case that political science has generated specific insights into American politics that simply cannot be gleaned from close journalistic coverage of current events.  What distinguishes political science from popular discourse about American politics and what findings should political scientists emphasize to correct popular misunderstandings about American politics?  Using several examples from contemporary politics (possibly including, but not limited to, the current election, Congressional gridlock, recent court cases, trends in policymaking), how does political science provide a distinctive understanding of American politics?

### Elitists versus Pluralists

> The study of American politics has often been marked by disputes over theory or method.  For example, the debate over elitist and pluralist explanations of political power in America or the debate over the value of rational choice as a general theoretical approach to the study of American politics.  In your response, first, identify an important debate over theory and/or method in at least two different substantive areas of study in American politics (e.g., Congress, the bureaucracy, voting, the courts, or economic policy) and explain what the scholarly debate was about.  Second, discuss whether these debates have served to advance or hinder our understanding of politics in these areas of study.

### Are academics part of the political elite?

> It can be argued that American politics plays out among two different classes of actors:  political elites and the general public.  Thinking about American politics and policymaking as a whole, discuss the relative influence of political elites and the broader American public.  Does the public drive our national politics and policymaking?  Or do political elites have most of the power in our political system and control both the agenda and much of the decision-making?  What larger theories, and which scholars, help us understand the tensions between mass democracy and elite politics, and the paradox of a normative commitment to political equality coexisting with unequal influence of elite, organized, and well-funded groups in modern American politics?


### Recent Classics

> What recent works in the study of American politics already are or are destined to become classics that will be cited by scholars and studied by future generations of graduate students?  To answer this question, identify at least five (5) recent scholarly works – books or journal articles published in the last 10 years or so – on different topics within American politics that you believe will be regarded as classic works by future political scientists.  For each, explain why the work you have chosen will become a classic by assessing how that work relates to prior research on the topic and advances our understanding of some significant aspect of American politics.

### Essential Themes & Controversies

> Undergraduate students taking American Government will typically use a text covering the Constitution, the branches of government, and political participation.  Based on your graduate work, make an argument for the essential themes and controversies that an instructor should communicate to these undergraduates.  Cite relevant authors in support of your choices.

## Short Questions

These shorter questions can usually be resolved within 4,500 words or so.

### Congress 1

> What do scholars know about how Congress actually works?  Using your knowledge of the scholarly literature on Congress, what pieces of research would you identify as the best for understanding how Congress functions?  In your response be sure to delineate the various functions that Congress performs, and identify and briefly describe the various foci of scholars who study “how Congress functions.”  Be sure to cite specific works to support your argument.

### Congress 2

> What are the most important scholarly studies on Congress?  To answer this question, identify at least 5, but no more than 10 books or articles written on some aspect of Congress that you believe are the most important scholarly works in the field.  Be sure to explain what these works tell us about Congress and why they are so important to scholars seeking to understand Congress.

### Electoral Connection

> In Federalist 51, James Madison observes that the electoral connection is the public’s “primary control on government.”  Thinking broadly about political science scholarship on American political institutions, and focusing on at least two national governmental institutions (e.g., Congress, the Presidency, the bureaucracy, the courts), answer the following:  Does the reelection incentive induce our national governmental institutions, and the actors within them, to be responsive to the public and public interests?  Does the electoral connection create systematic biases in governmental action?  Please provide a critical look at the scholarship underlying your answers.

### Electoral Connection 2

> In Federalist 51, James Madison observes that the electoral connection is the “primary control on government.”  Does the reelection incentive induce members of Congress to respond to constituents’ policy preferences?  Does the electoral connection create systematic biases in congressional policymaking that undermine Congress’s capacities as a legislative institution?

### Party politics, polarization, Congress

> In recent years, party polarization has increased significantly and many commentators have bemoaned this trend.  The increase of partisan polarization in congressional roll-call voting has been of particular concern.  How does the literature on Congress shed light on the likely effects of such polarization?  What do models of congressional leadership tell us about the causes of polarization and its likely consequences?  And, with unified government for the first time in a decade, does strong party government yield any benefits?  What are its costs?

### Political Participation 1

> In the November 2016 elections, as in all American elections, we observed dramatically large differences in the levels of participation of different groups of people among the broader American public.  What does the political science scholarship tell us about why some people participate in their political system more than others?  What does the scholarship tell us about the consequences of such differential participation for American politics and policymaking?  Should action be taken to address these differential participation rates?  If so, what remedies might help?

### Participate Meaningfully?

> One prerequisite of a truly democratic nation would be that average citizens are able to participate in politics in a meaningful fashion.  Based on your knowledge of the research literature on political participation in the United States, how would you assess American democracy?  That is, does the research on political participation suggest that all American citizens are able to participate effectively or are there serious problems with the nature of political participation in the U.S.?  Be sure to discuss key scholarly works on political participation in your response.

### Voter Suppression, Voter Participation, Election Rules and Reform, Electoral Behavior

> Undergirding much of the discussion of the behavior of the American electorate in the past few decades has been sizeable argumentation over existing election rules and reform.  From gerrymandering to nonpartisan primaries, motor voter registration to voter ID laws, what does the political science literature tell us about the links between electoral rules and electoral behavior?  Are claims that recent changes in election rules have led to skewed participation or unrepresentative results overblown or under theorized?

### What do Americans know about Politics?

> Survey after survey has shown that Americans are often at a loss to recall basic facts about their government and politics.  Less definitively understood is the degree to which this lack of political knowledge matters.  Are people able to make reasonable political decisions despite their ignorance?  Does the lack of information possessed by most Americans affect our politics?  Provide an overview of the scholarly debates that exist regarding these questions and bases on which scholars agree and disagree.  Ultimately, should we conclude that a healthy democracy depends on a well-informed electorate, or not?

### Voter Knowledge, Voter Choice

> Surely, one of the prerequisites of a truly democratic polity would be that average citizens know enough about their own policy preferences and the functioning of the political system to be able to participate in politics in a meaningful way.  Yet, many studies of American citizens have raised doubts about how much Americans know about politics or even how firmly they hold their own opinions.  Based on the scholarly research, what would you conclude about how well the average American is able to participate effectively in our political system?  In your response, be sure to discuss specific scholarly works and explain how these works have influenced your conclusions about American citizens.

### Voter Choice, Voter Decision Making, Electoral Behavior

> In November 2016, Americans elected a new president.  In your judgment, how well do we as scholars of American politics understand how individuals make voting decisions?  What are the major theories used to explain individual vote choice and how well are these theories supported by the empirical evidence?

### Why did Trump win?

> Political scientists and political observers alike were surprised by Trump’s political rise and his electoral success in 2016.  Scholars first expected that he would lose the nomination contest, and then that he would lose the general election.  Looking at the scholarship on political behavior and U.S. elections, explain why political scientists were, for the most part, surprised by Trump’s success.  What scholarship led us to believe he would fail?  At the same time, what scholarship can help explain Trump’s rise and his success in 2016?

### How Democratic are We? Public interests, Public will, Theories of Democracy

> Truly democratic political institutions are designed such that they reflect the public interest, and the diversity of public perspectives and interests, in their actions.  How democratic are American political institutions?  Focusing on TWO specific institutions or institutional structures (e.g., Congress, the Presidency, the Bureaucracy, the Courts, Federalism, etc.) explain what political science scholarship tell us about how well each meets a democratic ideal, and how and in what ways each falls short.  Ultimately, should we describe our institutions as sufficiently democratic or not?

### Bureaucratic Responsiveness

> While the courts are often described as reactive, other institutions, such as Congress and the bureaucracy are assumed to be more proactive.  Given the large and constantly growing literature on agenda-setting in the policy process as well as the various frameworks explaining interest group activity and Congressional action, how true is it that the bureaucracy in particular can be seen as truly proactive?  Do bureaucrats shape their policy domains or do they primarily attempt to balance and accommodate outside pressures?


### Bureaucracy, Administrative State

> Scholars of American politics often neglect the single largest element in U.S. government, the bureaucracy, leaving it to scholars of public administration as if less important.  However, there have been some Americanists who have taken an active interest in explaining how the need to control and even motivate the enormous federal bureaucracy has shaped such constitutional branches as Congress and the Presidency.  Explain how the development of large and complex federal bureaucracy in the post-World War II (and perhaps especially post Great Society) era has led to new understandings of Congress and the Presidency.  How has the regulatory welfare state changed the nature of political leadership, the different roles of legislators and chief executives, and the relationship between the constitutional branches?

### Bureaucratic Autonomy

> Perhaps unsurprisingly, the Trump Administration has already prompted great attention to the scope of bureaucratic autonomy and discretion in policy making and implementation.  What does the scholarly literature tell us about the nature, sources, and degree of bureaucratic autonomy in the policy process?  Will this be an Achilles heel for the Trump Administration or a source of strength?


### Approaches to Presidential Scholarship

> There are numerous ways to study the presidency.  For example, some scholars study institutional powers of the executive, while others focus on the characteristics of the particular individuals who have been elected president.  Based upon your knowledge of the scholarly literature on the presidency, what approach (or set of approaches) do you regard as the most fruitful for explaining the nature of the American presidency?


### Three Major Trends in Presidential Scholarship

> The study of the presidency has changed considerably over the past fifty years.  Identify three major trends in the study of the presidency since the 1950s.  Cite at least one major book or article to illustrate the unique approaches embraced during each of these three trends.  Evaluate the strengths and weaknesses of each trend.


### Imperial Presidency & Congress

> In 1885, Woodrow Wilson published Congressional Government, his description of a contemporary American politics dominated by Congress.  In 1973, Arthur Schlesinger published The Imperial Presidency, in which he described the Presidency as dominant.  Today, neither branch seems particularly capable of making the other yield to its own agenda.  Drawing on the literature on both the Congress and the Presidency, explain how each branch has developed advantages over the other as well as the restraints that have developed over the years that limit each branch.  A proper answer will include attention to both external and internal mechanisms that both enable and restrain each branches’ powers.

### Power of the Presidency:

> How powerful is the American presidency?  Some contend that the office is inherently weak and presidential power significantly limited.  Others contend the office is incredibly strong, possessing institutional powers to transform American politics and policy.  First, provide a thorough overview of scholarship on the power of the American presidency, including an assessment of the empirical evidence in support of different perspectives.  Second, in your judgment, is the presidency a very powerful office, or is the office inherently weak, and why?

### Presidential Power: Unilateral action in policymaking

> President Obama has received both praise from his allies and criticism from his opponents for his use of unilateral action in policymaking.  What does the political science literature tell us about presidential power and unilateral action?  Are Obama’s actions part of the tradition of presidential politics or a significant shift?  What does Obama’s use of unilateral action in the White House tell us about the power of the modern presidency?


### Pluralism, interest groups, and policy process

> In Federalist 10, James Madison famously argued that pluralism could save America from factionalism.  Yet, today it seems as if the policy process is both typified by pluralism and sometimes dominated by factionalism.  Drawing on the scholarship on both interest groups and the policy process, what conclusions can be drawn regarding how pluralism influences the policy process?  Make sure to review both the history of thinking about interest groups and how several different models of the policy process understand the role of interest groups.

### Racial and ethnic progress in American public policy

> Throughout U.S. history the dominant group (i.e. WASPs during the majority of U.S. history) has tried to adopt public policies to institutionalize racial or ethnic inequality to gain political advantages over minority groups.  Examples of such institutional domination include slavery imposed on African Americans, the forced relocation of American Indians, the exclusionary immigration laws such as the 1882 Chines Exclusion Act, and the 1924 National Origin Act against Southern and Eastern Europeans and Jews.  But the dominant WASPs also sometimes passed legislations in an attempt to protect the rights of the minority groups.  Examples of such equality-oriented legislation includes the 13th – 15th Constitutional Amendments, the Civil Rights Act of 1964 and Voting Rights Acts of 1965, which were all passed by majority-white Congresses.  Discuss how and why these policy changes took place in the U.S. history.  Is there a trend toward racial and ethnic progress in terms of American public policies over time?  Identify the most important political science literature in this area.

### Rational and Irrational Voting:

> From Aristotle of classic Greece to John Rawls of modern America, countless first-rate scholars have put their keen eyes on how humans behave in the political arenas.  Still there are too many questions unanswered.  Based on your understanding of the American politics, do humans act rationally when it comes to the issues of voting for a party?  If so, why do they sometimes make decisions that seem utterly irrational in politics?  Are they attracted to certain candidates’ special qualities that are difficult to quantify in rational terms?  Are voters for the most part calculating for their own economic gains when they decide politically?

### Institutionalism

> The study of institutions as institutions has had a significant revival in the last 30 years as new “institutionalisms” have emerged.  Identify and describe these new forms of institutionalism and explain how they have changed the study of American politics?  How have we come to recognize that institutions matter?  How have these new versions of institutionalism added value to political science?

### Biology, political behavior, socialization, race?

> Recently there has been a renewed interest in the relationship between biology and political behavior. Based on the new findings reported in the political science journals and scholarly books, does biology count at all when it comes to the decision of voting, participation in mass movements, or simply forming a political opinion?  Can citizens’ political behaviors be inherited from their parents?  Or are they actually a product of their own socialization process?  Does race matter?  Why or why not?


### Major Approaches to Policy Analysis

> Discuss approaches taken to public policy analysis.  What are the major theoretical approaches?  What are the forms of evidence used?  How should public policy analysis be conducted?  For whom?

### Two Policy Frameworks

> A number of frameworks have been used to analyze the process and outcomes of American public policy.  Among these frameworks are elitism, pluralism, neopluralism, incrementalism, feminism, subgovernments, policy process models, issue networks, advocacy coalitions, and others.  Identify two frameworks that you regard as especially useful for the study of public policy.  For each, explain how the framework approaches the study of public policy and evaluate its strengths and weaknesses as  tool for understanding the process and substance of public policy.

### Three frameworks/theories/models of policy-making & collective choice

>Scholars make use of frameworks, theories, and models in their attempts to explain the politics of policy-making processes and the collective authoritative public choices that come from them.  Distinguish among these three approaches to empirical inquiry, and discuss how they are interrelated, if at all; then describe the extent to which researchers have improved our understanding by applying them to specific substantive areas of public policy.

### One substantive area of public policy

>Choose one substantive area of American public policy, e.g., education, health care, criminal justice, or economic policy.  How have scholars attempted to explain public policy in this area?  Is there a consensus among scholars about how policy is made in this area or are there competing theories that seek to explain how policy is made and why we have the substantive outcomes we do in this policy area?  Based on your knowledge of the scholarly research in this policy area, how complete is our understanding and what additional information should scholars seek to learn?


### Lecturing on public policy

> Imagine that you have a representative sample of Americans captive for a single lecture on public policy.  What are they least likely to know about public policy making and implementation?  What would be most important to communicate to them?  Choose two different policy areas in your answer and support your decisions about what to emphasize with references to the public policy literature.

### Responsiveness of institutions, public - “collective” will (can it even be known or assumed):

>Political scholars are often concerned with the democratic responsiveness of political institutions; in other words, how well government reflects the will of the people.  How representative are our national American political institutions and our national government?  Focusing on two specific institutions (e.g., Congress, the Presidency, the Courts, the political parties, the bureaucracy), provide an overview of scholarly evidence suggesting our national institutions respond well to the public will, as well as scholarly evidence that they are less responsive.  On the whole, would you say American government is responsive to the people, or are there forces and structures that undermine this democratic responsiveness?

### Policy process field making progress?

> Critics argue that the public policy field has made little theoretical progress, finding itself mired in description and journalistic analysis.  Critique this assessment, evaluating the extent to which the major theoretical approaches to the study of public policy meet the standards for theory.  In doing so, identify the competing theoretical frameworks and their chief proponents, discuss their contributions and limitations, and suggest what is needed for them to make the transition from framework to theory.


### Political Parties and American Politics – Institutions & Behavior

> E.E. Schattschneider (1942) famously suggested that “modern democracy is unthinkable save in terms of political parties,” yet there is scholarly debate about the role parties play in American politics.  First, provide an overview of what we know about political parties and American politics – both its institutions and the behavior of the public.  Is American democracy “unthinkable” without political parties?

### What do Americans know about politics?

> Survey after survey has shown that Americans are often at a loss to recall basic facts about their government and politics.  Less definitely understood is the degree to which this lack of political knowledge matters.  Are people able to make reasonable political decision despite their ignorance?  Does the lack of information possessed by most Americans affect our politics?  What scholarly debates exist regarding these questions and on what bases do scholars disagree?  In your response, be sure to discuss specific scholarly works and explain whether the American public is capable of true self-governance?

### How do Americans decide how to vote?

> How do American voters decide how to vote?  This question has been central to the study of political behavior in the U.S. for at least 50 years.  How would you assess what political scientists know about vote choice?  Discuss the various theoretical explanation that have been offered as well as the evidence supporting these explanations.

### Political Campaigns

> Political campaigns are exciting, fascinating events that draw a significant amount of media and public interest.  Yet, to what degree can we say that campaigns matter?  Surveying the existing scholarship on public opinions, voting campaigns, and elections, what campaign effects have political scientists identified?  To what degree can we say that campaigns influence votes and election outcomes?  Ultimately, can we conclude that campaigns are a fundamentally important part of our democracy, or are they simply an intriguing sideshow?

### Link between Public Opinion and Public Policy

> How important are the attitudes and policy preferences of American citizens in determining what American governments at the state or national level actually do?  How have political scientists studied the linkage between public opinion and public policy and what have they found?  How well do political scientists understand the effect that public opinion has on public policy?

### Judicial Decision-Making I

> Compare and contrast the major theoretical approaches to understanding judicial decision-making, citing the relevant scholarly studies.  Make an argument for which approach you believe offers the best explanation of how judges actually make decisions.

### Judicial Decision Making II

> Compare and contract the major theoretical approaches to understanding judicial decision-making, citing relevant authors.  Make an argument for which approach you believe offers the best explanation of how judges make decisions and support your argument with concrete examples from any court setting with which you are familiar.


